-- =============================================================
-- Migration: Create / Sync schema "core"
-- Generated: 2026-07-10T10:36:15.783Z
-- Tables   : 21
-- Functions: 2
-- Strategy : Phase 0 = sequences
--            Phase 1 = tables/columns/constraints/indexes
--            Phase 2 = foreign keys (after all tables exist)
--            Phase 3 = functions & procedures (CREATE OR REPLACE)
-- =============================================================

-- Ensure schema exists
CREATE SCHEMA IF NOT EXISTS "core";

SET search_path TO "core", public;
-- =============================================================
-- PHASE 1: Create tables, columns, PK/unique/check, indexes
-- =============================================================
-- ============================================================
-- Table: "core"."apps"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."apps" (
  "apps_id" VARCHAR(30) NOT NULL,
  "apps_name" TEXT DEFAULT ''::text NOT NULL,
  "apps_url" TEXT,
  "apps_descr" TEXT,
  "apps_isdisabled" BOOLEAN DEFAULT false NOT NULL,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  "apps_directory" TEXT,
  CONSTRAINT "apps_pk" PRIMARY KEY ("apps_id"),
  CONSTRAINT "uq$core$apps$apps_name" UNIQUE ("apps_name")
);

-- Step 2: Add columns if not exists (safe to re-run)
-- WARNING: "apps_id" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."apps"
  ADD COLUMN IF NOT EXISTS "apps_id" VARCHAR(30);
-- TODO: UPDATE "core"."apps" SET "apps_id" = <value> WHERE "apps_id" IS NULL;
-- ALTER TABLE "core"."apps" ALTER COLUMN "apps_id" SET NOT NULL;
ALTER TABLE "core"."apps"
  ADD COLUMN IF NOT EXISTS "apps_name" TEXT DEFAULT ''::text NOT NULL;
ALTER TABLE "core"."apps"
  ADD COLUMN IF NOT EXISTS "apps_url" TEXT;
ALTER TABLE "core"."apps"
  ADD COLUMN IF NOT EXISTS "apps_descr" TEXT;
ALTER TABLE "core"."apps"
  ADD COLUMN IF NOT EXISTS "apps_isdisabled" BOOLEAN DEFAULT false NOT NULL;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."apps"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."apps" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."apps" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."apps"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."apps"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."apps"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;
ALTER TABLE "core"."apps"
  ADD COLUMN IF NOT EXISTS "apps_directory" TEXT;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'apps'
      AND constraint_name = 'apps_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."apps" ADD CONSTRAINT "apps_pk" PRIMARY KEY ("apps_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'apps'
      AND constraint_name = 'uq$core$apps$apps_name'
  ) THEN
    ALTER TABLE "core"."apps" ADD CONSTRAINT "uq$core$apps$apps_name" UNIQUE ("apps_name");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$apps$apps_name" ON "core"."apps" USING BTREE ("apps_name");

-- ======================================================================

-- ============================================================
-- Table: "core"."auth"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."auth" (
  "auth_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "auth_name" TEXT,
  "auth_label" TEXT,
  "auth_descr" TEXT,
  "user_id" INTEGER,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  "delegate_start" DATE DEFAULT now(),
  "delegate_end" DATE DEFAULT now(),
  "delegate_user_id" INTEGER,
  CONSTRAINT "auth_pk" PRIMARY KEY ("auth_id"),
  CONSTRAINT "uq$core$auth$auth_label" UNIQUE ("auth_label"),
  CONSTRAINT "uq$core$auth$auth_name" UNIQUE ("auth_name")
);

-- Step 2: Add columns if not exists (safe to re-run)
ALTER TABLE "core"."auth"
  ADD COLUMN IF NOT EXISTS "auth_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE "core"."auth"
  ADD COLUMN IF NOT EXISTS "auth_name" TEXT;
ALTER TABLE "core"."auth"
  ADD COLUMN IF NOT EXISTS "auth_label" TEXT;
ALTER TABLE "core"."auth"
  ADD COLUMN IF NOT EXISTS "auth_descr" TEXT;
ALTER TABLE "core"."auth"
  ADD COLUMN IF NOT EXISTS "user_id" INTEGER;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."auth"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."auth" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."auth" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."auth"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."auth"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."auth"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;
ALTER TABLE "core"."auth"
  ADD COLUMN IF NOT EXISTS "delegate_start" DATE DEFAULT now();
ALTER TABLE "core"."auth"
  ADD COLUMN IF NOT EXISTS "delegate_end" DATE DEFAULT now();
ALTER TABLE "core"."auth"
  ADD COLUMN IF NOT EXISTS "delegate_user_id" INTEGER;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'auth'
      AND constraint_name = 'auth_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."auth" ADD CONSTRAINT "auth_pk" PRIMARY KEY ("auth_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'auth'
      AND constraint_name = 'uq$core$auth$auth_label'
  ) THEN
    ALTER TABLE "core"."auth" ADD CONSTRAINT "uq$core$auth$auth_label" UNIQUE ("auth_label");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'auth'
      AND constraint_name = 'uq$core$auth$auth_name'
  ) THEN
    ALTER TABLE "core"."auth" ADD CONSTRAINT "uq$core$auth$auth_name" UNIQUE ("auth_name");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE INDEX IF NOT EXISTS "idx_fk$core$auth$delegate_user_id" ON "core"."auth" USING BTREE ("delegate_user_id");
CREATE INDEX IF NOT EXISTS "idx_fk$core$auth$user_id" ON "core"."auth" USING BTREE ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$auth$auth_label" ON "core"."auth" USING BTREE ("auth_label");
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$auth$auth_name" ON "core"."auth" USING BTREE ("auth_name");

-- Step 5: Column & table comments
COMMENT ON COLUMN "core"."auth"."_createby" IS 'user yang pertama kali membuat record ini';
COMMENT ON COLUMN "core"."auth"."_createdate" IS 'waktu record dibuat pertama kali';
COMMENT ON COLUMN "core"."auth"."_modifyby" IS 'user yang terakhir modifikasi record ini';
COMMENT ON COLUMN "core"."auth"."_modifydate" IS 'waktu terakhir record dimodifikasi';

-- ======================================================================

-- ============================================================
-- Table: "core"."doc"
-- ============================================================

-- Step 1: Create table if not exists
-- daftar document
CREATE TABLE IF NOT EXISTS "core"."doc" (
  "doc_id" VARCHAR(4) NOT NULL,
  "doc_name" TEXT,
  "doc_descr" TEXT,
  "doc_seqnum" INTEGER DEFAULT 0 NOT NULL,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  "doc_seqclust" SMALLINT DEFAULT 0 NOT NULL,
  "doc_prefix" TEXT,
  CONSTRAINT "doc_pk" PRIMARY KEY ("doc_id"),
  CONSTRAINT "uq$core$doc$doc_name" UNIQUE ("doc_name"),
  CONSTRAINT "uq$core$doc$doc_seqnum" UNIQUE ("doc_seqclust", "doc_seqnum")
);

-- Step 2: Add columns if not exists (safe to re-run)
-- WARNING: "doc_id" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."doc"
  ADD COLUMN IF NOT EXISTS "doc_id" VARCHAR(4);
-- TODO: UPDATE "core"."doc" SET "doc_id" = <value> WHERE "doc_id" IS NULL;
-- ALTER TABLE "core"."doc" ALTER COLUMN "doc_id" SET NOT NULL;
ALTER TABLE "core"."doc"
  ADD COLUMN IF NOT EXISTS "doc_name" TEXT;
ALTER TABLE "core"."doc"
  ADD COLUMN IF NOT EXISTS "doc_descr" TEXT;
ALTER TABLE "core"."doc"
  ADD COLUMN IF NOT EXISTS "doc_seqnum" INTEGER DEFAULT 0 NOT NULL;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."doc"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."doc" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."doc" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."doc"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."doc"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."doc"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;
ALTER TABLE "core"."doc"
  ADD COLUMN IF NOT EXISTS "doc_seqclust" SMALLINT DEFAULT 0 NOT NULL;
ALTER TABLE "core"."doc"
  ADD COLUMN IF NOT EXISTS "doc_prefix" TEXT;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'doc'
      AND constraint_name = 'doc_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."doc" ADD CONSTRAINT "doc_pk" PRIMARY KEY ("doc_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'doc'
      AND constraint_name = 'uq$core$doc$doc_name'
  ) THEN
    ALTER TABLE "core"."doc" ADD CONSTRAINT "uq$core$doc$doc_name" UNIQUE ("doc_name");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'doc'
      AND constraint_name = 'uq$core$doc$doc_seqnum'
  ) THEN
    ALTER TABLE "core"."doc" ADD CONSTRAINT "uq$core$doc$doc_seqnum" UNIQUE ("doc_seqclust", "doc_seqnum");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$doc$doc_name" ON "core"."doc" USING BTREE ("doc_name");
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$doc$doc_seqnum" ON "core"."doc" USING BTREE ("doc_seqclust", "doc_seqnum");

-- Step 5: Column & table comments
COMMENT ON TABLE "core"."doc" IS 'daftar document';
COMMENT ON COLUMN "core"."doc"."doc_descr" IS 'deskripsi dokumen';
COMMENT ON COLUMN "core"."doc"."doc_seqnum" IS 'nilai dalam sequencer';

-- ======================================================================

-- ============================================================
-- Table: "core"."generator"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."generator" (
  "generator_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "generator_appname" TEXT DEFAULT ''::text NOT NULL,
  "generator_modulename" TEXT DEFAULT ''::text NOT NULL,
  "generator_data" JSON NOT NULL,
  "_createby" INTEGER,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  CONSTRAINT "generator_pk" PRIMARY KEY ("generator_id"),
  CONSTRAINT "generator_name" UNIQUE ("generator_appname", "generator_modulename")
);

-- Step 2: Add columns if not exists (safe to re-run)
ALTER TABLE "core"."generator"
  ADD COLUMN IF NOT EXISTS "generator_id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE "core"."generator"
  ADD COLUMN IF NOT EXISTS "generator_appname" TEXT DEFAULT ''::text NOT NULL;
ALTER TABLE "core"."generator"
  ADD COLUMN IF NOT EXISTS "generator_modulename" TEXT DEFAULT ''::text NOT NULL;
-- WARNING: "generator_data" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."generator"
  ADD COLUMN IF NOT EXISTS "generator_data" JSON;
-- TODO: UPDATE "core"."generator" SET "generator_data" = <value> WHERE "generator_data" IS NULL;
-- ALTER TABLE "core"."generator" ALTER COLUMN "generator_data" SET NOT NULL;
ALTER TABLE "core"."generator"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
ALTER TABLE "core"."generator"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."generator"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."generator"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'generator'
      AND constraint_name = 'generator_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."generator" ADD CONSTRAINT "generator_pk" PRIMARY KEY ("generator_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'generator'
      AND constraint_name = 'generator_name'
  ) THEN
    ALTER TABLE "core"."generator" ADD CONSTRAINT "generator_name" UNIQUE ("generator_appname", "generator_modulename");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE UNIQUE INDEX IF NOT EXISTS "generator_name" ON "core"."generator" USING BTREE ("generator_appname", "generator_modulename");

-- ======================================================================

-- ============================================================
-- Table: "core"."group"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."group" (
  "group_id" INTEGER NOT NULL,
  "group_name" TEXT,
  "group_descr" TEXT,
  "group_isdisabled" BOOLEAN DEFAULT false NOT NULL,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  CONSTRAINT "group_pk" PRIMARY KEY ("group_id"),
  CONSTRAINT "uq$core$group$group_name" UNIQUE ("group_name")
);

-- Step 2: Add columns if not exists (safe to re-run)
-- WARNING: "group_id" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."group"
  ADD COLUMN IF NOT EXISTS "group_id" INTEGER;
-- TODO: UPDATE "core"."group" SET "group_id" = <value> WHERE "group_id" IS NULL;
-- ALTER TABLE "core"."group" ALTER COLUMN "group_id" SET NOT NULL;
ALTER TABLE "core"."group"
  ADD COLUMN IF NOT EXISTS "group_name" TEXT;
ALTER TABLE "core"."group"
  ADD COLUMN IF NOT EXISTS "group_descr" TEXT;
ALTER TABLE "core"."group"
  ADD COLUMN IF NOT EXISTS "group_isdisabled" BOOLEAN DEFAULT false NOT NULL;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."group"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."group" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."group" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."group"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."group"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."group"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'group'
      AND constraint_name = 'group_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."group" ADD CONSTRAINT "group_pk" PRIMARY KEY ("group_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'group'
      AND constraint_name = 'uq$core$group$group_name'
  ) THEN
    ALTER TABLE "core"."group" ADD CONSTRAINT "uq$core$group$group_name" UNIQUE ("group_name");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$group$group_name" ON "core"."group" USING BTREE ("group_name");

-- Step 5: Column & table comments
COMMENT ON COLUMN "core"."group"."_createby" IS 'user yang pertama kali membuat record ini';
COMMENT ON COLUMN "core"."group"."_createdate" IS 'waktu record dibuat pertama kali';
COMMENT ON COLUMN "core"."group"."_modifyby" IS 'user yang terakhir modifikasi record ini';
COMMENT ON COLUMN "core"."group"."_modifydate" IS 'waktu terakhir record dimodifikasi';

-- ======================================================================

-- ============================================================
-- Table: "core"."groupprogram"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."groupprogram" (
  "groupprogram_id" BIGINT NOT NULL,
  "program_id" INTEGER,
  "groupprogram_isdisabled" BOOLEAN DEFAULT false NOT NULL,
  "group_id" INTEGER,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  CONSTRAINT "groupprogram_pk" PRIMARY KEY ("groupprogram_id"),
  CONSTRAINT "uq$core$groupprogram$groupprogram_pair" UNIQUE ("group_id", "program_id")
);

-- Step 2: Add columns if not exists (safe to re-run)
-- WARNING: "groupprogram_id" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."groupprogram"
  ADD COLUMN IF NOT EXISTS "groupprogram_id" BIGINT;
-- TODO: UPDATE "core"."groupprogram" SET "groupprogram_id" = <value> WHERE "groupprogram_id" IS NULL;
-- ALTER TABLE "core"."groupprogram" ALTER COLUMN "groupprogram_id" SET NOT NULL;
ALTER TABLE "core"."groupprogram"
  ADD COLUMN IF NOT EXISTS "program_id" INTEGER;
ALTER TABLE "core"."groupprogram"
  ADD COLUMN IF NOT EXISTS "groupprogram_isdisabled" BOOLEAN DEFAULT false NOT NULL;
ALTER TABLE "core"."groupprogram"
  ADD COLUMN IF NOT EXISTS "group_id" INTEGER;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."groupprogram"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."groupprogram" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."groupprogram" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."groupprogram"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."groupprogram"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."groupprogram"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'groupprogram'
      AND constraint_name = 'groupprogram_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."groupprogram" ADD CONSTRAINT "groupprogram_pk" PRIMARY KEY ("groupprogram_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'groupprogram'
      AND constraint_name = 'uq$core$groupprogram$groupprogram_pair'
  ) THEN
    ALTER TABLE "core"."groupprogram" ADD CONSTRAINT "uq$core$groupprogram$groupprogram_pair" UNIQUE ("group_id", "program_id");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE INDEX IF NOT EXISTS "idx_fk$core$groupprogram$group_id" ON "core"."groupprogram" USING BTREE ("group_id");
CREATE INDEX IF NOT EXISTS "idx_fk$core$groupprogram$program_id" ON "core"."groupprogram" USING BTREE ("program_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$groupprogram$groupprogram_pair" ON "core"."groupprogram" USING BTREE ("group_id", "program_id");

-- Step 5: Column & table comments
COMMENT ON COLUMN "core"."groupprogram"."_createby" IS 'user yang pertama kali membuat record ini';
COMMENT ON COLUMN "core"."groupprogram"."_createdate" IS 'waktu record dibuat pertama kali';
COMMENT ON COLUMN "core"."groupprogram"."_modifyby" IS 'user yang terakhir modifikasi record ini';
COMMENT ON COLUMN "core"."groupprogram"."_modifydate" IS 'waktu terakhir record dimodifikasi';

-- ======================================================================

-- ============================================================
-- Table: "core"."interface"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."interface" (
  "interface_id" SMALLINT NOT NULL,
  "interface_name" TEXT,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  CONSTRAINT "interface_pk" PRIMARY KEY ("interface_id"),
  CONSTRAINT "uq$core$interface$interface_name" UNIQUE ("interface_name")
);

-- Step 2: Add columns if not exists (safe to re-run)
-- WARNING: "interface_id" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."interface"
  ADD COLUMN IF NOT EXISTS "interface_id" SMALLINT;
-- TODO: UPDATE "core"."interface" SET "interface_id" = <value> WHERE "interface_id" IS NULL;
-- ALTER TABLE "core"."interface" ALTER COLUMN "interface_id" SET NOT NULL;
ALTER TABLE "core"."interface"
  ADD COLUMN IF NOT EXISTS "interface_name" TEXT;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."interface"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."interface" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."interface" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."interface"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."interface"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."interface"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'interface'
      AND constraint_name = 'interface_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."interface" ADD CONSTRAINT "interface_pk" PRIMARY KEY ("interface_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'interface'
      AND constraint_name = 'uq$core$interface$interface_name'
  ) THEN
    ALTER TABLE "core"."interface" ADD CONSTRAINT "uq$core$interface$interface_name" UNIQUE ("interface_name");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$interface$interface_name" ON "core"."interface" USING BTREE ("interface_name");

-- Step 5: Column & table comments
COMMENT ON COLUMN "core"."interface"."_createby" IS 'user yang pertama kali membuat record ini';
COMMENT ON COLUMN "core"."interface"."_createdate" IS 'waktu record dibuat pertama kali';
COMMENT ON COLUMN "core"."interface"."_modifyby" IS 'user yang terakhir modifikasi record ini';
COMMENT ON COLUMN "core"."interface"."_modifydate" IS 'waktu terakhir record dimodifikasi';

-- ======================================================================

-- ============================================================
-- Table: "core"."permission"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."permission" (
  "permission_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "permission_name" TEXT,
  "permission_isdisabled" BOOLEAN DEFAULT false NOT NULL,
  "permission_descr" TEXT,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  "permission_defaultvalue" TEXT,
  CONSTRAINT "permission_pk" PRIMARY KEY ("permission_id"),
  CONSTRAINT "uq$core$permission$permission_name" UNIQUE ("permission_name")
);

-- Step 2: Add columns if not exists (safe to re-run)
ALTER TABLE "core"."permission"
  ADD COLUMN IF NOT EXISTS "permission_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE "core"."permission"
  ADD COLUMN IF NOT EXISTS "permission_name" TEXT;
ALTER TABLE "core"."permission"
  ADD COLUMN IF NOT EXISTS "permission_isdisabled" BOOLEAN DEFAULT false NOT NULL;
ALTER TABLE "core"."permission"
  ADD COLUMN IF NOT EXISTS "permission_descr" TEXT;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."permission"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."permission" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."permission" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."permission"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."permission"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."permission"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;
ALTER TABLE "core"."permission"
  ADD COLUMN IF NOT EXISTS "permission_defaultvalue" TEXT;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'permission'
      AND constraint_name = 'permission_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."permission" ADD CONSTRAINT "permission_pk" PRIMARY KEY ("permission_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'permission'
      AND constraint_name = 'uq$core$permission$permission_name'
  ) THEN
    ALTER TABLE "core"."permission" ADD CONSTRAINT "uq$core$permission$permission_name" UNIQUE ("permission_name");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$permission$permission_name" ON "core"."permission" USING BTREE ("permission_name");

-- Step 5: Column & table comments
COMMENT ON COLUMN "core"."permission"."_createby" IS 'user yang pertama kali membuat record ini';
COMMENT ON COLUMN "core"."permission"."_createdate" IS 'waktu record dibuat pertama kali';
COMMENT ON COLUMN "core"."permission"."_modifyby" IS 'user yang terakhir modifikasi record ini';
COMMENT ON COLUMN "core"."permission"."_modifydate" IS 'waktu terakhir record dimodifikasi';

-- ======================================================================

-- ============================================================
-- Table: "core"."program"
-- ============================================================

-- Step 1: Create table if not exists
-- daftar program
CREATE TABLE IF NOT EXISTS "core"."program" (
  "program_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "program_title" TEXT,
  "apps_id" VARCHAR(30),
  "program_name" TEXT,
  "program_variance" TEXT,
  "programgroup_id" INTEGER,
  "program_descr" TEXT,
  "program_icon" TEXT,
  "program_isdisabled" BOOLEAN DEFAULT false NOT NULL,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  "generator_id" INTEGER,
  CONSTRAINT "program_pk" PRIMARY KEY ("program_id"),
  CONSTRAINT "uq$core$program$program_name" UNIQUE ("program_name", "program_variance")
);

-- Step 2: Add columns if not exists (safe to re-run)
ALTER TABLE "core"."program"
  ADD COLUMN IF NOT EXISTS "program_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE "core"."program"
  ADD COLUMN IF NOT EXISTS "program_title" TEXT;
ALTER TABLE "core"."program"
  ADD COLUMN IF NOT EXISTS "apps_id" VARCHAR(30);
ALTER TABLE "core"."program"
  ADD COLUMN IF NOT EXISTS "program_name" TEXT;
ALTER TABLE "core"."program"
  ADD COLUMN IF NOT EXISTS "program_variance" TEXT;
ALTER TABLE "core"."program"
  ADD COLUMN IF NOT EXISTS "programgroup_id" INTEGER;
ALTER TABLE "core"."program"
  ADD COLUMN IF NOT EXISTS "program_descr" TEXT;
ALTER TABLE "core"."program"
  ADD COLUMN IF NOT EXISTS "program_icon" TEXT;
ALTER TABLE "core"."program"
  ADD COLUMN IF NOT EXISTS "program_isdisabled" BOOLEAN DEFAULT false NOT NULL;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."program"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."program" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."program" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."program"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."program"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."program"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;
ALTER TABLE "core"."program"
  ADD COLUMN IF NOT EXISTS "generator_id" INTEGER;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'program'
      AND constraint_name = 'program_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."program" ADD CONSTRAINT "program_pk" PRIMARY KEY ("program_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'program'
      AND constraint_name = 'uq$core$program$program_name'
  ) THEN
    ALTER TABLE "core"."program" ADD CONSTRAINT "uq$core$program$program_name" UNIQUE ("program_name", "program_variance");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE INDEX IF NOT EXISTS "idx_fk$core$program$apps_id" ON "core"."program" USING BTREE ("apps_id");
CREATE INDEX IF NOT EXISTS "idx_fk$core$program$generator_id" ON "core"."program" USING BTREE ("generator_id");
CREATE INDEX IF NOT EXISTS "idx_fk$core$program$programgroup_id" ON "core"."program" USING BTREE ("programgroup_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$program$program_name" ON "core"."program" USING BTREE ("program_name", "program_variance");

-- Step 5: Column & table comments
COMMENT ON TABLE "core"."program" IS 'daftar program';

-- ======================================================================

-- ============================================================
-- Table: "core"."programgroup"
-- ============================================================

-- Step 1: Create table if not exists
-- daftar grouping program hierarki
CREATE TABLE IF NOT EXISTS "core"."programgroup" (
  "programgroup_id" INTEGER NOT NULL,
  "programgroup_name" TEXT,
  "programgroup_descr" TEXT,
  "programgroup_isparent" BOOLEAN DEFAULT false NOT NULL,
  "programgroup_parent" INTEGER,
  "programgroup_pathid" TEXT,
  "programgroup_path" TEXT,
  "programgroup_level" INTEGER DEFAULT 0 NOT NULL,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  "programgroup_icon" TEXT,
  CONSTRAINT "programgroup_pk" PRIMARY KEY ("programgroup_id"),
  CONSTRAINT "uq$core$programgroup$programgroup_name" UNIQUE ("programgroup_parent", "programgroup_name")
);

-- Step 2: Add columns if not exists (safe to re-run)
-- WARNING: "programgroup_id" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."programgroup"
  ADD COLUMN IF NOT EXISTS "programgroup_id" INTEGER;
-- TODO: UPDATE "core"."programgroup" SET "programgroup_id" = <value> WHERE "programgroup_id" IS NULL;
-- ALTER TABLE "core"."programgroup" ALTER COLUMN "programgroup_id" SET NOT NULL;
ALTER TABLE "core"."programgroup"
  ADD COLUMN IF NOT EXISTS "programgroup_name" TEXT;
ALTER TABLE "core"."programgroup"
  ADD COLUMN IF NOT EXISTS "programgroup_descr" TEXT;
ALTER TABLE "core"."programgroup"
  ADD COLUMN IF NOT EXISTS "programgroup_isparent" BOOLEAN DEFAULT false NOT NULL;
ALTER TABLE "core"."programgroup"
  ADD COLUMN IF NOT EXISTS "programgroup_parent" INTEGER;
ALTER TABLE "core"."programgroup"
  ADD COLUMN IF NOT EXISTS "programgroup_pathid" TEXT;
ALTER TABLE "core"."programgroup"
  ADD COLUMN IF NOT EXISTS "programgroup_path" TEXT;
ALTER TABLE "core"."programgroup"
  ADD COLUMN IF NOT EXISTS "programgroup_level" INTEGER DEFAULT 0 NOT NULL;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."programgroup"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."programgroup" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."programgroup" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."programgroup"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."programgroup"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."programgroup"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;
ALTER TABLE "core"."programgroup"
  ADD COLUMN IF NOT EXISTS "programgroup_icon" TEXT;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'programgroup'
      AND constraint_name = 'programgroup_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."programgroup" ADD CONSTRAINT "programgroup_pk" PRIMARY KEY ("programgroup_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'programgroup'
      AND constraint_name = 'uq$core$programgroup$programgroup_name'
  ) THEN
    ALTER TABLE "core"."programgroup" ADD CONSTRAINT "uq$core$programgroup$programgroup_name" UNIQUE ("programgroup_parent", "programgroup_name");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE INDEX IF NOT EXISTS "idx_fk$core$programgroup$programgroup_parent" ON "core"."programgroup" USING BTREE ("programgroup_parent");
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$programgroup$programgroup_name" ON "core"."programgroup" USING BTREE ("programgroup_parent", "programgroup_name");

-- Step 5: Column & table comments
COMMENT ON TABLE "core"."programgroup" IS 'daftar grouping program hierarki';
COMMENT ON COLUMN "core"."programgroup"."_createby" IS 'user yang pertama kali membuat record ini';
COMMENT ON COLUMN "core"."programgroup"."_createdate" IS 'waktu record dibuat pertama kali';
COMMENT ON COLUMN "core"."programgroup"."_modifyby" IS 'user yang terakhir modifikasi record ini';
COMMENT ON COLUMN "core"."programgroup"."_modifydate" IS 'waktu terakhir record dimodifikasi';

-- ======================================================================

-- ============================================================
-- Table: "core"."role"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."role" (
  "role_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "role_name" TEXT,
  "role_isdisabled" BOOLEAN DEFAULT false NOT NULL,
  "role_descr" TEXT,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  "role_priority" INTEGER DEFAULT 0 NOT NULL,
  CONSTRAINT "role_pk" PRIMARY KEY ("role_id"),
  CONSTRAINT "uq$core$role$role_name" UNIQUE ("role_name")
);

-- Step 2: Add columns if not exists (safe to re-run)
ALTER TABLE "core"."role"
  ADD COLUMN IF NOT EXISTS "role_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE "core"."role"
  ADD COLUMN IF NOT EXISTS "role_name" TEXT;
ALTER TABLE "core"."role"
  ADD COLUMN IF NOT EXISTS "role_isdisabled" BOOLEAN DEFAULT false NOT NULL;
ALTER TABLE "core"."role"
  ADD COLUMN IF NOT EXISTS "role_descr" TEXT;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."role"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."role" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."role" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."role"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."role"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."role"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;
ALTER TABLE "core"."role"
  ADD COLUMN IF NOT EXISTS "role_priority" INTEGER DEFAULT 0 NOT NULL;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'role'
      AND constraint_name = 'role_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."role" ADD CONSTRAINT "role_pk" PRIMARY KEY ("role_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'role'
      AND constraint_name = 'uq$core$role$role_name'
  ) THEN
    ALTER TABLE "core"."role" ADD CONSTRAINT "uq$core$role$role_name" UNIQUE ("role_name");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$role$role_name" ON "core"."role" USING BTREE ("role_name");

-- Step 5: Column & table comments
COMMENT ON COLUMN "core"."role"."_createby" IS 'user yang pertama kali membuat record ini';
COMMENT ON COLUMN "core"."role"."_createdate" IS 'waktu record dibuat pertama kali';
COMMENT ON COLUMN "core"."role"."_modifyby" IS 'user yang terakhir modifikasi record ini';
COMMENT ON COLUMN "core"."role"."_modifydate" IS 'waktu terakhir record dimodifikasi';

-- ======================================================================

-- ============================================================
-- Table: "core"."rolepermission"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."rolepermission" (
  "rolepermission_id" BIGINT NOT NULL,
  "permission_id" INTEGER,
  "permission_value" TEXT,
  "role_id" INTEGER,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  CONSTRAINT "rolepermission_pk" PRIMARY KEY ("rolepermission_id"),
  CONSTRAINT "uq$core$rolepermission$rolepermission_pair" UNIQUE ("role_id", "permission_id")
);

-- Step 2: Add columns if not exists (safe to re-run)
-- WARNING: "rolepermission_id" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."rolepermission"
  ADD COLUMN IF NOT EXISTS "rolepermission_id" BIGINT;
-- TODO: UPDATE "core"."rolepermission" SET "rolepermission_id" = <value> WHERE "rolepermission_id" IS NULL;
-- ALTER TABLE "core"."rolepermission" ALTER COLUMN "rolepermission_id" SET NOT NULL;
ALTER TABLE "core"."rolepermission"
  ADD COLUMN IF NOT EXISTS "permission_id" INTEGER;
ALTER TABLE "core"."rolepermission"
  ADD COLUMN IF NOT EXISTS "permission_value" TEXT;
ALTER TABLE "core"."rolepermission"
  ADD COLUMN IF NOT EXISTS "role_id" INTEGER;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."rolepermission"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."rolepermission" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."rolepermission" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."rolepermission"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."rolepermission"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."rolepermission"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'rolepermission'
      AND constraint_name = 'rolepermission_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."rolepermission" ADD CONSTRAINT "rolepermission_pk" PRIMARY KEY ("rolepermission_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'rolepermission'
      AND constraint_name = 'uq$core$rolepermission$rolepermission_pair'
  ) THEN
    ALTER TABLE "core"."rolepermission" ADD CONSTRAINT "uq$core$rolepermission$rolepermission_pair" UNIQUE ("role_id", "permission_id");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE INDEX IF NOT EXISTS "idx_fk$core$rolepermission$permission_id" ON "core"."rolepermission" USING BTREE ("permission_id");
CREATE INDEX IF NOT EXISTS "idx_fk$core$rolepermission$role_id" ON "core"."rolepermission" USING BTREE ("role_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$rolepermission$rolepermission_pair" ON "core"."rolepermission" USING BTREE ("role_id", "permission_id");

-- Step 5: Column & table comments
COMMENT ON COLUMN "core"."rolepermission"."_createby" IS 'user yang pertama kali membuat record ini';
COMMENT ON COLUMN "core"."rolepermission"."_createdate" IS 'waktu record dibuat pertama kali';
COMMENT ON COLUMN "core"."rolepermission"."_modifyby" IS 'user yang terakhir modifikasi record ini';
COMMENT ON COLUMN "core"."rolepermission"."_modifydate" IS 'waktu terakhir record dimodifikasi';

-- ======================================================================

-- ============================================================
-- Table: "core"."sequencer_doc"
-- ============================================================

-- Step 1: Create table if not exists
-- sequencer document
CREATE TABLE IF NOT EXISTS "core"."sequencer_doc" (
  "sequencer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sequencer_year" INTEGER DEFAULT 0 NOT NULL,
  "sequencer_month" INTEGER DEFAULT 0 NOT NULL,
  "sequencer_seqnum" INTEGER DEFAULT 0 NOT NULL,
  "sequencer_block" INTEGER DEFAULT 0 NOT NULL,
  "sequencer_cluster" INTEGER DEFAULT 0 NOT NULL,
  "sequencer_number" INTEGER DEFAULT 0 NOT NULL,
  "sequencer_lastdate" DATE DEFAULT now(),
  "sequencer_remark" TEXT,
  "_createby" BIGINT NOT NULL,
  "_createdate" TIMESTAMPTZ NOT NULL,
  "_modifyby" BIGINT,
  "_modifydate" TIMESTAMPTZ,
  CONSTRAINT "sequencer_pk" PRIMARY KEY ("sequencer_id"),
  CONSTRAINT "uq$core$sequencer$sequencer_line" UNIQUE ("sequencer_year", "sequencer_month", "sequencer_seqnum", "sequencer_block", "sequencer_cluster")
);

-- Step 2: Add columns if not exists (safe to re-run)
ALTER TABLE "core"."sequencer_doc"
  ADD COLUMN IF NOT EXISTS "sequencer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE "core"."sequencer_doc"
  ADD COLUMN IF NOT EXISTS "sequencer_year" INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE "core"."sequencer_doc"
  ADD COLUMN IF NOT EXISTS "sequencer_month" INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE "core"."sequencer_doc"
  ADD COLUMN IF NOT EXISTS "sequencer_seqnum" INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE "core"."sequencer_doc"
  ADD COLUMN IF NOT EXISTS "sequencer_block" INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE "core"."sequencer_doc"
  ADD COLUMN IF NOT EXISTS "sequencer_cluster" INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE "core"."sequencer_doc"
  ADD COLUMN IF NOT EXISTS "sequencer_number" INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE "core"."sequencer_doc"
  ADD COLUMN IF NOT EXISTS "sequencer_lastdate" DATE DEFAULT now();
ALTER TABLE "core"."sequencer_doc"
  ADD COLUMN IF NOT EXISTS "sequencer_remark" TEXT;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."sequencer_doc"
  ADD COLUMN IF NOT EXISTS "_createby" BIGINT;
-- TODO: UPDATE "core"."sequencer_doc" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."sequencer_doc" ALTER COLUMN "_createby" SET NOT NULL;
-- WARNING: "_createdate" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."sequencer_doc"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ;
-- TODO: UPDATE "core"."sequencer_doc" SET "_createdate" = <value> WHERE "_createdate" IS NULL;
-- ALTER TABLE "core"."sequencer_doc" ALTER COLUMN "_createdate" SET NOT NULL;
ALTER TABLE "core"."sequencer_doc"
  ADD COLUMN IF NOT EXISTS "_modifyby" BIGINT;
ALTER TABLE "core"."sequencer_doc"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'sequencer_doc'
      AND constraint_name = 'sequencer_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."sequencer_doc" ADD CONSTRAINT "sequencer_pk" PRIMARY KEY ("sequencer_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'sequencer_doc'
      AND constraint_name = 'uq$core$sequencer$sequencer_line'
  ) THEN
    ALTER TABLE "core"."sequencer_doc" ADD CONSTRAINT "uq$core$sequencer$sequencer_line" UNIQUE ("sequencer_year", "sequencer_month", "sequencer_seqnum", "sequencer_block", "sequencer_cluster");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$sequencer$sequencer_line" ON "core"."sequencer_doc" USING BTREE ("sequencer_year", "sequencer_month", "sequencer_seqnum", "sequencer_block", "sequencer_cluster");

-- Step 5: Column & table comments
COMMENT ON TABLE "core"."sequencer_doc" IS 'sequencer document';

-- ======================================================================

-- ============================================================
-- Table: "core"."sequencer_line"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."sequencer_line" (
  "sequencer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sequencer_cluster" INTEGER DEFAULT 0 NOT NULL,
  "sequencer_seqnum" INTEGER DEFAULT 0 NOT NULL,
  "sequencer_year" INTEGER DEFAULT 0 NOT NULL,
  "sequencer_month" INTEGER DEFAULT 0 NOT NULL,
  "sequencer_number" INTEGER DEFAULT 0 NOT NULL,
  "sequencer_lastdate" DATE DEFAULT now(),
  "sequencer_remark" TEXT,
  "_createby" BIGINT NOT NULL,
  "_createdate" TIMESTAMPTZ NOT NULL,
  "_modifyby" BIGINT,
  "_modifydate" TIMESTAMPTZ,
  CONSTRAINT "sequencerline_pk" PRIMARY KEY ("sequencer_id")
);

-- Step 2: Add columns if not exists (safe to re-run)
ALTER TABLE "core"."sequencer_line"
  ADD COLUMN IF NOT EXISTS "sequencer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE "core"."sequencer_line"
  ADD COLUMN IF NOT EXISTS "sequencer_cluster" INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE "core"."sequencer_line"
  ADD COLUMN IF NOT EXISTS "sequencer_seqnum" INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE "core"."sequencer_line"
  ADD COLUMN IF NOT EXISTS "sequencer_year" INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE "core"."sequencer_line"
  ADD COLUMN IF NOT EXISTS "sequencer_month" INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE "core"."sequencer_line"
  ADD COLUMN IF NOT EXISTS "sequencer_number" INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE "core"."sequencer_line"
  ADD COLUMN IF NOT EXISTS "sequencer_lastdate" DATE DEFAULT now();
ALTER TABLE "core"."sequencer_line"
  ADD COLUMN IF NOT EXISTS "sequencer_remark" TEXT;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."sequencer_line"
  ADD COLUMN IF NOT EXISTS "_createby" BIGINT;
-- TODO: UPDATE "core"."sequencer_line" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."sequencer_line" ALTER COLUMN "_createby" SET NOT NULL;
-- WARNING: "_createdate" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."sequencer_line"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ;
-- TODO: UPDATE "core"."sequencer_line" SET "_createdate" = <value> WHERE "_createdate" IS NULL;
-- ALTER TABLE "core"."sequencer_line" ALTER COLUMN "_createdate" SET NOT NULL;
ALTER TABLE "core"."sequencer_line"
  ADD COLUMN IF NOT EXISTS "_modifyby" BIGINT;
ALTER TABLE "core"."sequencer_line"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'sequencer_line'
      AND constraint_name = 'sequencerline_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."sequencer_line" ADD CONSTRAINT "sequencerline_pk" PRIMARY KEY ("sequencer_id");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$sequencerline$sequencer_line" ON "core"."sequencer_line" USING BTREE ("sequencer_cluster", "sequencer_seqnum", "sequencer_year", "sequencer_month");

-- ======================================================================

-- ============================================================
-- Table: "core"."setting"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."setting" (
  "setting_id" VARCHAR(30) NOT NULL,
  "setting_value" TEXT,
  "setting_descr" TEXT,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  CONSTRAINT "setting_pk" PRIMARY KEY ("setting_id")
);

-- Step 2: Add columns if not exists (safe to re-run)
-- WARNING: "setting_id" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."setting"
  ADD COLUMN IF NOT EXISTS "setting_id" VARCHAR(30);
-- TODO: UPDATE "core"."setting" SET "setting_id" = <value> WHERE "setting_id" IS NULL;
-- ALTER TABLE "core"."setting" ALTER COLUMN "setting_id" SET NOT NULL;
ALTER TABLE "core"."setting"
  ADD COLUMN IF NOT EXISTS "setting_value" TEXT;
ALTER TABLE "core"."setting"
  ADD COLUMN IF NOT EXISTS "setting_descr" TEXT;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."setting"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."setting" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."setting" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."setting"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."setting"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."setting"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'setting'
      AND constraint_name = 'setting_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."setting" ADD CONSTRAINT "setting_pk" PRIMARY KEY ("setting_id");
  END IF;
END $$;

-- Step 5: Column & table comments
COMMENT ON COLUMN "core"."setting"."_createby" IS 'user yang pertama kali membuat record ini';
COMMENT ON COLUMN "core"."setting"."_createdate" IS 'waktu record dibuat pertama kali';
COMMENT ON COLUMN "core"."setting"."_modifyby" IS 'user yang terakhir modifikasi record ini';
COMMENT ON COLUMN "core"."setting"."_modifydate" IS 'waktu terakhir record dimodifikasi';

-- ======================================================================

-- ============================================================
-- Table: "core"."user"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."user" (
  "user_id" INTEGER NOT NULL,
  "user_name" VARCHAR(30),
  "user_nickname" TEXT,
  "user_fullname" TEXT,
  "user_email" TEXT,
  "user_password" TEXT,
  "user_isdisabled" BOOLEAN DEFAULT false NOT NULL,
  "user_isdev" BOOLEAN DEFAULT false NOT NULL,
  "user_isallowallprogram" BOOLEAN DEFAULT false NOT NULL,
  "user_isshowallprogram" BOOLEAN DEFAULT false NOT NULL,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  CONSTRAINT "user_pk" PRIMARY KEY ("user_id"),
  CONSTRAINT "uq$core$user$user_name" UNIQUE ("user_name")
);

-- Step 2: Add columns if not exists (safe to re-run)
-- WARNING: "user_id" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."user"
  ADD COLUMN IF NOT EXISTS "user_id" INTEGER;
-- TODO: UPDATE "core"."user" SET "user_id" = <value> WHERE "user_id" IS NULL;
-- ALTER TABLE "core"."user" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE "core"."user"
  ADD COLUMN IF NOT EXISTS "user_name" VARCHAR(30);
ALTER TABLE "core"."user"
  ADD COLUMN IF NOT EXISTS "user_nickname" TEXT;
ALTER TABLE "core"."user"
  ADD COLUMN IF NOT EXISTS "user_fullname" TEXT;
ALTER TABLE "core"."user"
  ADD COLUMN IF NOT EXISTS "user_email" TEXT;
ALTER TABLE "core"."user"
  ADD COLUMN IF NOT EXISTS "user_password" TEXT;
ALTER TABLE "core"."user"
  ADD COLUMN IF NOT EXISTS "user_isdisabled" BOOLEAN DEFAULT false NOT NULL;
ALTER TABLE "core"."user"
  ADD COLUMN IF NOT EXISTS "user_isdev" BOOLEAN DEFAULT false NOT NULL;
ALTER TABLE "core"."user"
  ADD COLUMN IF NOT EXISTS "user_isallowallprogram" BOOLEAN DEFAULT false NOT NULL;
ALTER TABLE "core"."user"
  ADD COLUMN IF NOT EXISTS "user_isshowallprogram" BOOLEAN DEFAULT false NOT NULL;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."user"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."user" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."user" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."user"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."user"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."user"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'user'
      AND constraint_name = 'user_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."user" ADD CONSTRAINT "user_pk" PRIMARY KEY ("user_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'user'
      AND constraint_name = 'uq$core$user$user_name'
  ) THEN
    ALTER TABLE "core"."user" ADD CONSTRAINT "uq$core$user$user_name" UNIQUE ("user_name");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$user$user_name" ON "core"."user" USING BTREE ("user_name");

-- Step 5: Column & table comments
COMMENT ON COLUMN "core"."user"."_createby" IS 'user yang pertama kali membuat record ini';
COMMENT ON COLUMN "core"."user"."_createdate" IS 'waktu record dibuat pertama kali';
COMMENT ON COLUMN "core"."user"."_modifyby" IS 'user yang terakhir modifikasi record ini';
COMMENT ON COLUMN "core"."user"."_modifydate" IS 'waktu terakhir record dimodifikasi';

-- ======================================================================

-- ============================================================
-- Table: "core"."userfavouriteprogram"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."userfavouriteprogram" (
  "userfavouriteprogram_id" BIGINT NOT NULL,
  "program_id" INTEGER,
  "user_id" INTEGER,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  CONSTRAINT "userfavouriteprogram_pk" PRIMARY KEY ("userfavouriteprogram_id"),
  CONSTRAINT "uq$core$userfavouriteprogram$userfavouriteprogram_pair" UNIQUE ("userfavouriteprogram_id", "program_id")
);

-- Step 2: Add columns if not exists (safe to re-run)
-- WARNING: "userfavouriteprogram_id" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."userfavouriteprogram"
  ADD COLUMN IF NOT EXISTS "userfavouriteprogram_id" BIGINT;
-- TODO: UPDATE "core"."userfavouriteprogram" SET "userfavouriteprogram_id" = <value> WHERE "userfavouriteprogram_id" IS NULL;
-- ALTER TABLE "core"."userfavouriteprogram" ALTER COLUMN "userfavouriteprogram_id" SET NOT NULL;
ALTER TABLE "core"."userfavouriteprogram"
  ADD COLUMN IF NOT EXISTS "program_id" INTEGER;
ALTER TABLE "core"."userfavouriteprogram"
  ADD COLUMN IF NOT EXISTS "user_id" INTEGER;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."userfavouriteprogram"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."userfavouriteprogram" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."userfavouriteprogram" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."userfavouriteprogram"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."userfavouriteprogram"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."userfavouriteprogram"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'userfavouriteprogram'
      AND constraint_name = 'userfavouriteprogram_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."userfavouriteprogram" ADD CONSTRAINT "userfavouriteprogram_pk" PRIMARY KEY ("userfavouriteprogram_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'userfavouriteprogram'
      AND constraint_name = 'uq$core$userfavouriteprogram$userfavouriteprogram_pair'
  ) THEN
    ALTER TABLE "core"."userfavouriteprogram" ADD CONSTRAINT "uq$core$userfavouriteprogram$userfavouriteprogram_pair" UNIQUE ("userfavouriteprogram_id", "program_id");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE INDEX IF NOT EXISTS "idx_fk$core$userfavouriteprogram$program_id" ON "core"."userfavouriteprogram" USING BTREE ("program_id");
CREATE INDEX IF NOT EXISTS "idx_fk$core$userfavouriteprogram$user_id" ON "core"."userfavouriteprogram" USING BTREE ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$userfavouriteprogram$userfavouriteprogram_pair" ON "core"."userfavouriteprogram" USING BTREE ("userfavouriteprogram_id", "program_id");

-- Step 5: Column & table comments
COMMENT ON COLUMN "core"."userfavouriteprogram"."_createby" IS 'user yang pertama kali membuat record ini';
COMMENT ON COLUMN "core"."userfavouriteprogram"."_createdate" IS 'waktu record dibuat pertama kali';
COMMENT ON COLUMN "core"."userfavouriteprogram"."_modifyby" IS 'user yang terakhir modifikasi record ini';
COMMENT ON COLUMN "core"."userfavouriteprogram"."_modifydate" IS 'waktu terakhir record dimodifikasi';

-- ======================================================================

-- ============================================================
-- Table: "core"."usergroup"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."usergroup" (
  "usergroup_id" BIGINT NOT NULL,
  "group_id" INTEGER,
  "usergroup_isdisabled" BOOLEAN DEFAULT false NOT NULL,
  "user_id" INTEGER,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  CONSTRAINT "usergroup_pk" PRIMARY KEY ("usergroup_id")
);

-- Step 2: Add columns if not exists (safe to re-run)
-- WARNING: "usergroup_id" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."usergroup"
  ADD COLUMN IF NOT EXISTS "usergroup_id" BIGINT;
-- TODO: UPDATE "core"."usergroup" SET "usergroup_id" = <value> WHERE "usergroup_id" IS NULL;
-- ALTER TABLE "core"."usergroup" ALTER COLUMN "usergroup_id" SET NOT NULL;
ALTER TABLE "core"."usergroup"
  ADD COLUMN IF NOT EXISTS "group_id" INTEGER;
ALTER TABLE "core"."usergroup"
  ADD COLUMN IF NOT EXISTS "usergroup_isdisabled" BOOLEAN DEFAULT false NOT NULL;
ALTER TABLE "core"."usergroup"
  ADD COLUMN IF NOT EXISTS "user_id" INTEGER;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."usergroup"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."usergroup" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."usergroup" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."usergroup"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."usergroup"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."usergroup"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'usergroup'
      AND constraint_name = 'usergroup_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."usergroup" ADD CONSTRAINT "usergroup_pk" PRIMARY KEY ("usergroup_id");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE INDEX IF NOT EXISTS "idx_fk$core$usergroup$group_id" ON "core"."usergroup" USING BTREE ("group_id");
CREATE INDEX IF NOT EXISTS "idx_fk$core$usergroup$user_id" ON "core"."usergroup" USING BTREE ("user_id");

-- Step 5: Column & table comments
COMMENT ON COLUMN "core"."usergroup"."_createby" IS 'user yang pertama kali membuat record ini';
COMMENT ON COLUMN "core"."usergroup"."_createdate" IS 'waktu record dibuat pertama kali';
COMMENT ON COLUMN "core"."usergroup"."_modifyby" IS 'user yang terakhir modifikasi record ini';
COMMENT ON COLUMN "core"."usergroup"."_modifydate" IS 'waktu terakhir record dimodifikasi';

-- ======================================================================

-- ============================================================
-- Table: "core"."userlogin"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."userlogin" (
  "userlogin_id" BIGINT NOT NULL,
  "userlogin_name" TEXT,
  "user_id" INTEGER,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  CONSTRAINT "userlogin_pk" PRIMARY KEY ("userlogin_id"),
  CONSTRAINT "uq$core$userlogin$userlogin_name" UNIQUE ("userlogin_name")
);

-- Step 2: Add columns if not exists (safe to re-run)
-- WARNING: "userlogin_id" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."userlogin"
  ADD COLUMN IF NOT EXISTS "userlogin_id" BIGINT;
-- TODO: UPDATE "core"."userlogin" SET "userlogin_id" = <value> WHERE "userlogin_id" IS NULL;
-- ALTER TABLE "core"."userlogin" ALTER COLUMN "userlogin_id" SET NOT NULL;
ALTER TABLE "core"."userlogin"
  ADD COLUMN IF NOT EXISTS "userlogin_name" TEXT;
ALTER TABLE "core"."userlogin"
  ADD COLUMN IF NOT EXISTS "user_id" INTEGER;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."userlogin"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."userlogin" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."userlogin" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."userlogin"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."userlogin"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."userlogin"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'userlogin'
      AND constraint_name = 'userlogin_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."userlogin" ADD CONSTRAINT "userlogin_pk" PRIMARY KEY ("userlogin_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'userlogin'
      AND constraint_name = 'uq$core$userlogin$userlogin_name'
  ) THEN
    ALTER TABLE "core"."userlogin" ADD CONSTRAINT "uq$core$userlogin$userlogin_name" UNIQUE ("userlogin_name");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE INDEX IF NOT EXISTS "idx_fk$core$userlogin$user_id" ON "core"."userlogin" USING BTREE ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$userlogin$userlogin_name" ON "core"."userlogin" USING BTREE ("userlogin_name");

-- Step 5: Column & table comments
COMMENT ON COLUMN "core"."userlogin"."_createby" IS 'user yang pertama kali membuat record ini';
COMMENT ON COLUMN "core"."userlogin"."_createdate" IS 'waktu record dibuat pertama kali';
COMMENT ON COLUMN "core"."userlogin"."_modifyby" IS 'user yang terakhir modifikasi record ini';
COMMENT ON COLUMN "core"."userlogin"."_modifydate" IS 'waktu terakhir record dimodifikasi';

-- ======================================================================

-- ============================================================
-- Table: "core"."userprop"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."userprop" (
  "userprop_id" BIGINT NOT NULL,
  "userprop_name" VARCHAR(90),
  "userprop_value" CHAR(30),
  "user_id" INTEGER,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  CONSTRAINT "userprop_pk" PRIMARY KEY ("userprop_id"),
  CONSTRAINT "uq$core$userprop$userprop_name" UNIQUE ("userprop_id", "userprop_name")
);

-- Step 2: Add columns if not exists (safe to re-run)
-- WARNING: "userprop_id" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."userprop"
  ADD COLUMN IF NOT EXISTS "userprop_id" BIGINT;
-- TODO: UPDATE "core"."userprop" SET "userprop_id" = <value> WHERE "userprop_id" IS NULL;
-- ALTER TABLE "core"."userprop" ALTER COLUMN "userprop_id" SET NOT NULL;
ALTER TABLE "core"."userprop"
  ADD COLUMN IF NOT EXISTS "userprop_name" VARCHAR(90);
ALTER TABLE "core"."userprop"
  ADD COLUMN IF NOT EXISTS "userprop_value" CHAR(30);
ALTER TABLE "core"."userprop"
  ADD COLUMN IF NOT EXISTS "user_id" INTEGER;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."userprop"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."userprop" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."userprop" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."userprop"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."userprop"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."userprop"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'userprop'
      AND constraint_name = 'userprop_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."userprop" ADD CONSTRAINT "userprop_pk" PRIMARY KEY ("userprop_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'userprop'
      AND constraint_name = 'uq$core$userprop$userprop_name'
  ) THEN
    ALTER TABLE "core"."userprop" ADD CONSTRAINT "uq$core$userprop$userprop_name" UNIQUE ("userprop_id", "userprop_name");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE INDEX IF NOT EXISTS "idx_fk$core$userprop$user_id" ON "core"."userprop" USING BTREE ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$userprop$userprop_name" ON "core"."userprop" USING BTREE ("userprop_id", "userprop_name");

-- Step 5: Column & table comments
COMMENT ON COLUMN "core"."userprop"."_createby" IS 'user yang pertama kali membuat record ini';
COMMENT ON COLUMN "core"."userprop"."_createdate" IS 'waktu record dibuat pertama kali';
COMMENT ON COLUMN "core"."userprop"."_modifyby" IS 'user yang terakhir modifikasi record ini';
COMMENT ON COLUMN "core"."userprop"."_modifydate" IS 'waktu terakhir record dimodifikasi';

-- ======================================================================

-- ============================================================
-- Table: "core"."userrole"
-- ============================================================

-- Step 1: Create table if not exists
CREATE TABLE IF NOT EXISTS "core"."userrole" (
  "userrole_id" BIGINT NOT NULL,
  "role_id" INTEGER,
  "user_id" INTEGER,
  "_createby" INTEGER NOT NULL,
  "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL,
  "_modifyby" INTEGER,
  "_modifydate" TIMESTAMPTZ,
  CONSTRAINT "userrole_pk" PRIMARY KEY ("userrole_id"),
  CONSTRAINT "uq$core$userrole$userrole_pair" UNIQUE ("user_id", "role_id")
);

-- Step 2: Add columns if not exists (safe to re-run)
-- WARNING: "userrole_id" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."userrole"
  ADD COLUMN IF NOT EXISTS "userrole_id" BIGINT;
-- TODO: UPDATE "core"."userrole" SET "userrole_id" = <value> WHERE "userrole_id" IS NULL;
-- ALTER TABLE "core"."userrole" ALTER COLUMN "userrole_id" SET NOT NULL;
ALTER TABLE "core"."userrole"
  ADD COLUMN IF NOT EXISTS "role_id" INTEGER;
ALTER TABLE "core"."userrole"
  ADD COLUMN IF NOT EXISTS "user_id" INTEGER;
-- WARNING: "_createby" is NOT NULL without DEFAULT.
-- Adding as NULL first; you must backfill before setting NOT NULL.
ALTER TABLE "core"."userrole"
  ADD COLUMN IF NOT EXISTS "_createby" INTEGER;
-- TODO: UPDATE "core"."userrole" SET "_createby" = <value> WHERE "_createby" IS NULL;
-- ALTER TABLE "core"."userrole" ALTER COLUMN "_createby" SET NOT NULL;
ALTER TABLE "core"."userrole"
  ADD COLUMN IF NOT EXISTS "_createdate" TIMESTAMPTZ DEFAULT now() NOT NULL;
ALTER TABLE "core"."userrole"
  ADD COLUMN IF NOT EXISTS "_modifyby" INTEGER;
ALTER TABLE "core"."userrole"
  ADD COLUMN IF NOT EXISTS "_modifydate" TIMESTAMPTZ;

-- Step 3: Add PK / unique / check constraints if not exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'userrole'
      AND constraint_name = 'userrole_pk' AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE "core"."userrole" ADD CONSTRAINT "userrole_pk" PRIMARY KEY ("userrole_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'userrole'
      AND constraint_name = 'uq$core$userrole$userrole_pair'
  ) THEN
    ALTER TABLE "core"."userrole" ADD CONSTRAINT "uq$core$userrole$userrole_pair" UNIQUE ("user_id", "role_id");
  END IF;
END $$;

-- Step 4: Create indexes if not exists
CREATE INDEX IF NOT EXISTS "idx_fk$core$userrole$role_id" ON "core"."userrole" USING BTREE ("role_id");
CREATE INDEX IF NOT EXISTS "idx_fk$core$userrole$user_id" ON "core"."userrole" USING BTREE ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq$core$userrole$userrole_pair" ON "core"."userrole" USING BTREE ("user_id", "role_id");

-- Step 5: Column & table comments
COMMENT ON COLUMN "core"."userrole"."_createby" IS 'user yang pertama kali membuat record ini';
COMMENT ON COLUMN "core"."userrole"."_createdate" IS 'waktu record dibuat pertama kali';
COMMENT ON COLUMN "core"."userrole"."_modifyby" IS 'user yang terakhir modifikasi record ini';
COMMENT ON COLUMN "core"."userrole"."_modifydate" IS 'waktu terakhir record dimodifikasi';

-- =============================================================
-- PHASE 2: Foreign key constraints (all tables already exist)
-- =============================================================
-- FK for "core"."auth"
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'auth'
      AND constraint_name = 'fk$core$auth$delegate_user_id'
  ) THEN
    ALTER TABLE "core"."auth"
      ADD CONSTRAINT "fk$core$auth$delegate_user_id" FOREIGN KEY ("delegate_user_id")
      REFERENCES "core"."user" ("user_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'auth'
      AND constraint_name = 'fk$core$auth$user_id'
  ) THEN
    ALTER TABLE "core"."auth"
      ADD CONSTRAINT "fk$core$auth$user_id" FOREIGN KEY ("user_id")
      REFERENCES "core"."user" ("user_id");
  END IF;
END $$;
-- ----------------------------------------------------------------------

-- FK for "core"."groupprogram"
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'groupprogram'
      AND constraint_name = 'fk$core$groupprogram$group_id'
  ) THEN
    ALTER TABLE "core"."groupprogram"
      ADD CONSTRAINT "fk$core$groupprogram$group_id" FOREIGN KEY ("group_id")
      REFERENCES "core"."group" ("group_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'groupprogram'
      AND constraint_name = 'fk$core$groupprogram$program_id'
  ) THEN
    ALTER TABLE "core"."groupprogram"
      ADD CONSTRAINT "fk$core$groupprogram$program_id" FOREIGN KEY ("program_id")
      REFERENCES "core"."program" ("program_id");
  END IF;
END $$;
-- ----------------------------------------------------------------------

-- FK for "core"."program"
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'program'
      AND constraint_name = 'fk$core$program$apps_id'
  ) THEN
    ALTER TABLE "core"."program"
      ADD CONSTRAINT "fk$core$program$apps_id" FOREIGN KEY ("apps_id")
      REFERENCES "core"."apps" ("apps_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'program'
      AND constraint_name = 'fk$core$program$generator_id'
  ) THEN
    ALTER TABLE "core"."program"
      ADD CONSTRAINT "fk$core$program$generator_id" FOREIGN KEY ("generator_id")
      REFERENCES "core"."generator" ("generator_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'program'
      AND constraint_name = 'fk$core$program$programgroup_id'
  ) THEN
    ALTER TABLE "core"."program"
      ADD CONSTRAINT "fk$core$program$programgroup_id" FOREIGN KEY ("programgroup_id")
      REFERENCES "core"."programgroup" ("programgroup_id");
  END IF;
END $$;
-- ----------------------------------------------------------------------

-- FK for "core"."programgroup"
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'programgroup'
      AND constraint_name = 'fk$core$programgroup$programgroup_parent'
  ) THEN
    ALTER TABLE "core"."programgroup"
      ADD CONSTRAINT "fk$core$programgroup$programgroup_parent" FOREIGN KEY ("programgroup_parent")
      REFERENCES "core"."programgroup" ("programgroup_id");
  END IF;
END $$;
-- ----------------------------------------------------------------------

-- FK for "core"."rolepermission"
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'rolepermission'
      AND constraint_name = 'fk$core$rolepermission$permission_id'
  ) THEN
    ALTER TABLE "core"."rolepermission"
      ADD CONSTRAINT "fk$core$rolepermission$permission_id" FOREIGN KEY ("permission_id")
      REFERENCES "core"."permission" ("permission_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'rolepermission'
      AND constraint_name = 'fk$core$rolepermission$role_id'
  ) THEN
    ALTER TABLE "core"."rolepermission"
      ADD CONSTRAINT "fk$core$rolepermission$role_id" FOREIGN KEY ("role_id")
      REFERENCES "core"."role" ("role_id");
  END IF;
END $$;
-- ----------------------------------------------------------------------

-- FK for "core"."userfavouriteprogram"
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'userfavouriteprogram'
      AND constraint_name = 'fk$core$userfavouriteprogram$program_id'
  ) THEN
    ALTER TABLE "core"."userfavouriteprogram"
      ADD CONSTRAINT "fk$core$userfavouriteprogram$program_id" FOREIGN KEY ("program_id")
      REFERENCES "core"."program" ("program_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'userfavouriteprogram'
      AND constraint_name = 'fk$core$userfavouriteprogram$user_id'
  ) THEN
    ALTER TABLE "core"."userfavouriteprogram"
      ADD CONSTRAINT "fk$core$userfavouriteprogram$user_id" FOREIGN KEY ("user_id")
      REFERENCES "core"."user" ("user_id");
  END IF;
END $$;
-- ----------------------------------------------------------------------

-- FK for "core"."usergroup"
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'usergroup'
      AND constraint_name = 'fk$core$usergroup$group_id'
  ) THEN
    ALTER TABLE "core"."usergroup"
      ADD CONSTRAINT "fk$core$usergroup$group_id" FOREIGN KEY ("group_id")
      REFERENCES "core"."group" ("group_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'usergroup'
      AND constraint_name = 'fk$core$usergroup$user_id'
  ) THEN
    ALTER TABLE "core"."usergroup"
      ADD CONSTRAINT "fk$core$usergroup$user_id" FOREIGN KEY ("user_id")
      REFERENCES "core"."user" ("user_id");
  END IF;
END $$;
-- ----------------------------------------------------------------------

-- FK for "core"."userlogin"
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'userlogin'
      AND constraint_name = 'fk$core$userlogin$user_id'
  ) THEN
    ALTER TABLE "core"."userlogin"
      ADD CONSTRAINT "fk$core$userlogin$user_id" FOREIGN KEY ("user_id")
      REFERENCES "core"."user" ("user_id");
  END IF;
END $$;
-- ----------------------------------------------------------------------

-- FK for "core"."userprop"
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'userprop'
      AND constraint_name = 'fk$core$userprop$user_id'
  ) THEN
    ALTER TABLE "core"."userprop"
      ADD CONSTRAINT "fk$core$userprop$user_id" FOREIGN KEY ("user_id")
      REFERENCES "core"."user" ("user_id");
  END IF;
END $$;
-- ----------------------------------------------------------------------

-- FK for "core"."userrole"
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'userrole'
      AND constraint_name = 'fk$core$userrole$role_id'
  ) THEN
    ALTER TABLE "core"."userrole"
      ADD CONSTRAINT "fk$core$userrole$role_id" FOREIGN KEY ("role_id")
      REFERENCES "core"."role" ("role_id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_schema = 'core' AND table_name = 'userrole'
      AND constraint_name = 'fk$core$userrole$user_id'
  ) THEN
    ALTER TABLE "core"."userrole"
      ADD CONSTRAINT "fk$core$userrole$user_id" FOREIGN KEY ("user_id")
      REFERENCES "core"."user" ("user_id");
  END IF;
END $$;
-- =============================================================
-- PHASE 3: Functions & Procedures (CREATE OR REPLACE — idempotent)
-- =============================================================
-- ------------------------------------------------------------
-- FUNCTION: get_user_permission(in_user_id integer, in_permission_name text)
-- Returns : TABLE(permission_id integer, permission_name text, permission_value text, role_name text, role_priority integer)
-- Language: plpgsql
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION core.get_user_permission(in_user_id integer, in_permission_name text)
 RETURNS TABLE(permission_id integer, permission_name text, permission_value text, role_name text, role_priority integer)
 LANGUAGE plpgsql
AS $function$

begin
	
	return query
	select 
	E.permission_id, 
	E.permission_name, 
    D.permission_value,
	C.role_name,
	C.role_priority	
	from core."user" A inner join core."userrole" B on B.user_id=A.user_id
                       inner join core."role" C on C.role_id=B.role_id
					   inner join core."rolepermission" D on D.role_id=C.role_id	
					   inner join core."permission" E on E.permission_id=D.permission_id
	where
	    A.user_id = in_user_id
	and E.permission_name=in_permission_name
	and C.role_isdisabled=false

	;
	

end;
$function$;

-- ------------------------------------------------------------
-- FUNCTION: get_user_programs(in_user_id integer)
-- Returns : TABLE(id integer, title text, url text, icon text, type text, level integer, path text, parent integer)
-- Language: plpgsql
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION core.get_user_programs(in_user_id integer)
 RETURNS TABLE(id integer, title text, url text, icon text, type text, level integer, path text, parent integer)
 LANGUAGE plpgsql
AS $function$


declare
	showallprogram bool;


begin
	
	drop table if exists temp_program;
	create temp table temp_program (
		id int,
		title text,
		url text,
		icon text,
		type text,
		level int,
		path text,
		parent int
	);


	-- cek apakah user boleh lihat semua program
	select user_isshowallprogram from core."user" where user_id =  in_user_id
	into showallprogram;



	if showallprogram=true then

		-- ambil semua program yang ada
		insert into temp_program
		(id, title, url, icon, type, level, path, parent)
		select distinct 
		D.program_id as id,
		D.program_title as title,
		concat(E.apps_url, '/', D.program_name, '?variance=' , D.program_variance) as url,
		case when D.program_icon='' then '' else concat(E.apps_url, '/', D.program_icon) end as icon,
		'1' as type,
		coalesce(F.programgroup_level, 1) as level,
		F.programgroup_path as path,
		D.programgroup_id
		from core."program" D inner join core."apps" E on  E.apps_id = D.apps_id and D.program_isdisabled = false
						   left join core."programgroup" F on F.programgroup_id = D.programgroup_id; 

	else

		-- ambil program hanya yang dipunyai user
		insert into temp_program
		(id, title, url, icon, type, level, path, parent)
		select distinct 
		D.program_id as id,
		D.program_title as title,
		concat(E.apps_url, '/', D.program_name, '?variance=' , D.program_variance) as url,
		case when D.program_icon='' then '' else concat(E.apps_url, '/', D.program_icon) end as icon,
		'1' as type,
		coalesce(F.programgroup_level, 1) as level,
		F.programgroup_path as path,
		D.programgroup_id 
		from core."user" A inner join core."usergroup" B on B.user_id  = A.user_id and B.usergroup_isdisabled = false
		                   inner join core."groupprogram" C on C.group_id = B.group_id  and C.groupprogram_isdisabled = false
		                   inner join core."program" D on D.program_id = C.program_id and D.program_isdisabled = false
		                   inner join core."apps" E on  E.apps_id = D.apps_id
						   left join core."programgroup" F on F.programgroup_id = D.programgroup_id 	
		where A.user_id = in_user_id;

	end if;

	

	-- ambil hierarki group
	with recursive program_hierarchy as (
	  select 
	    src.programgroup_id,
	    src.programgroup_name,
	    src.programgroup_parent,
		src.programgroup_pathid,
	    src.programgroup_path,
	    src.programgroup_icon,
		src.programgroup_level
	  from core.programgroup src
	  where src.programgroup_id in (select tmp.parent from temp_program tmp)
	
	  union
	
	  select 
	    pg.programgroup_id,
	    pg.programgroup_name,
	    pg.programgroup_parent,
		pg.programgroup_pathid,
	    pg.programgroup_path,
	    pg.programgroup_icon,
 		pg.programgroup_level

	  from core.programgroup pg inner join program_hierarchy ph 
	       on ph.programgroup_parent = pg.programgroup_id
	)
	
	insert into temp_program
	(id, title, url, icon, type, level, path, parent)
	select 
	ph.programgroup_id as id, 
	ph.programgroup_name as title, 
	'' as url,
	ph.programgroup_icon as icon,
	'0' as type , 
	ph.programgroup_level as level, 
	ph.programgroup_path, 
	ph.programgroup_parent
	from program_hierarchy ph
	order by ph.programgroup_path;


	return query
	select 
	X.id, 
	X.title, 
	X.url, 
	X.icon, 
	case when X.type='0' then 'group' else 'program' end as type, 
	X.level, 
	X.path,
	X.parent
	from temp_program X
	order by X.path nulls last, X.type, X.title;
	
end;
$function$;
