-- auth.sql


/* =============================================
 * CREATE TABLE core."auth"
 * ============================================*/
create table core."auth" (
	auth_id int generated by default as identity,
	constraint auth_pk primary key (auth_id)
);
comment on table core."auth" is '';	


-- =============================================
-- FIELD: auth_name text
-- =============================================
-- ADD auth_name
alter table core."auth" add auth_name text  ;
comment on column core."auth".auth_name is '';

-- MODIFY auth_name
alter table core."auth"
	alter column auth_name type text,
	ALTER COLUMN auth_name DROP DEFAULT,
	ALTER COLUMN auth_name DROP NOT NULL;
comment on column core."auth".auth_name is '';


-- =============================================
-- FIELD: auth_label text
-- =============================================
-- ADD auth_label
alter table core."auth" add auth_label text  ;
comment on column core."auth".auth_label is '';

-- MODIFY auth_label
alter table core."auth"
	alter column auth_label type text,
	ALTER COLUMN auth_label DROP DEFAULT,
	ALTER COLUMN auth_label DROP NOT NULL;
comment on column core."auth".auth_label is '';


-- =============================================
-- FIELD: auth_descr text
-- =============================================
-- ADD auth_descr
alter table core."auth" add auth_descr text  ;
comment on column core."auth".auth_descr is '';

-- MODIFY auth_descr
alter table core."auth"
	alter column auth_descr type text,
	ALTER COLUMN auth_descr DROP DEFAULT,
	ALTER COLUMN auth_descr DROP NOT NULL;
comment on column core."auth".auth_descr is '';


-- =============================================
-- FIELD: user_id int
-- =============================================
-- ADD user_id
alter table core."auth" add user_id int  ;
comment on column core."auth".user_id is '';

-- MODIFY user_id
alter table core."auth"
	alter column user_id type int,
	ALTER COLUMN user_id DROP DEFAULT,
	ALTER COLUMN user_id DROP NOT NULL;
comment on column core."auth".user_id is '';


-- =============================================
-- FIELD: delegate_user_id int
-- =============================================
-- ADD delegate_user_id
alter table core."auth" add delegate_user_id int  ;
comment on column core."auth".delegate_user_id is '';

-- MODIFY delegate_user_id
alter table core."auth"
	alter column delegate_user_id type int,
	ALTER COLUMN delegate_user_id DROP DEFAULT,
	ALTER COLUMN delegate_user_id DROP NOT NULL;
comment on column core."auth".delegate_user_id is '';


-- =============================================
-- FIELD: delegate_start date
-- =============================================
-- ADD delegate_start
alter table core."auth" add delegate_start date  default now();
comment on column core."auth".delegate_start is '';

-- MODIFY delegate_start
alter table core."auth"
	alter column delegate_start type date,
	ALTER COLUMN delegate_start SET DEFAULT now(),
	ALTER COLUMN delegate_start DROP NOT NULL;
comment on column core."auth".delegate_start is '';


-- =============================================
-- FIELD: delegate_end date
-- =============================================
-- ADD delegate_end
alter table core."auth" add delegate_end date  default now();
comment on column core."auth".delegate_end is '';

-- MODIFY delegate_end
alter table core."auth"
	alter column delegate_end type date,
	ALTER COLUMN delegate_end SET DEFAULT now(),
	ALTER COLUMN delegate_end DROP NOT NULL;
comment on column core."auth".delegate_end is '';


-- =============================================
-- FIELD: _createby integer
-- =============================================
-- ADD _createby
alter table core."auth" add _createby integer not null ;
comment on column core."auth"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table core."auth"
	alter column _createby type integer,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column core."auth"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table core."auth" add _createdate timestamp with time zone not null default now();
comment on column core."auth"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table core."auth"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate SET DEFAULT now(),
	ALTER COLUMN _createdate SET NOT NULL;
comment on column core."auth"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby integer
-- =============================================
-- ADD _modifyby
alter table core."auth" add _modifyby integer  ;
comment on column core."auth"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table core."auth"
	alter column _modifyby type integer,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column core."auth"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table core."auth" add _modifydate timestamp with time zone  ;
comment on column core."auth"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table core."auth"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column core."auth"._modifydate is 'waktu terakhir record dimodifikasi';




-- =============================================
-- FOREIGN KEY CONSTRAINT
-- =============================================
-- Drop Existing Foreign Key Constraint 
ALTER TABLE core."auth" DROP CONSTRAINT fk$core$auth$user_id;
ALTER TABLE core."auth" DROP CONSTRAINT fk$core$auth$delegate_user_id;


-- Add Foreign Key Constraint  
ALTER TABLE core."auth"
	ADD CONSTRAINT fk$core$auth$user_id
	FOREIGN KEY (user_id)
	REFERENCES core."user"(user_id);


-- Add As Index, drop dulu jika sudah ada
DROP INDEX IF EXISTS core.idx_fk$core$auth$user_id;
CREATE INDEX idx_fk$core$auth$user_id ON core."auth"(user_id);	


ALTER TABLE core."auth"
	ADD CONSTRAINT fk$core$auth$delegate_user_id
	FOREIGN KEY (delegate_user_id)
	REFERENCES core."user"(user_id);


-- Add As Index, drop dulu jika sudah ada
DROP INDEX IF EXISTS core.idx_fk$core$auth$delegate_user_id;
CREATE INDEX idx_fk$core$auth$delegate_user_id ON core."auth"(delegate_user_id);	

	


-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table core."auth"
	drop constraint uq$core$auth$auth_name;

alter table core."auth"
	drop constraint uq$core$auth$auth_label;
	

-- Add unique index 
alter table  core."auth"
	add constraint uq$core$auth$auth_name unique (auth_name); 

alter table  core."auth"
	add constraint uq$core$auth$auth_label unique (auth_label); 

