/***************************************************************** 
 * this script is generated by fgta5 generator version 1.2
 * DO NOT modify this script! All modification will lost on regeneration
 **************************************************************** */

import pgp from 'pg-promise';

import db from '@agung_dhewe/webapps/src/db.js'
import Api from '@agung_dhewe/webapps/src/api.js'
import sqlUtil from '@agung_dhewe/pgsqlc'
import context from '@agung_dhewe/webapps/src/context.js'  
import logger from '@agung_dhewe/webapps/src/logger.js'
import { createSequencerLine } from '@agung_dhewe/webapps/src/sequencerline.js' 

import * as Extender from './extenders/customer.apiext.js'

const moduleName = 'customer'
const headerSectionName = 'header'
const headerTableName = 'public.customer' 
const customerdiscTableName = 'public.customerdisc'  	

// api: account
export default class extends Api {
	constructor(req, res, next) {
		super(req, res, next);
		Api.cekLogin(req)
	}


	// dipanggil dengan model snake syntax
	// contoh: header-list
	//         header-open-data
	async init(body) { return await customer_init(this, body) }

	// extender call
	async execute(body) { return await customer_execute(this, body) }

	// header
	async headerList(body) { return await customer_headerList(this, body) }
	async headerOpen(body) { return await customer_headerOpen(this, body) }
	async headerUpdate(body) { return await customer_headerUpdate(this, body)}
	async headerCreate(body) { return await customer_headerCreate(this, body)}
	async headerDelete(body) { return await customer_headerDelete(this, body) }

	
	// customerdisc	
	async customerdiscList(body) { return await customer_customerdiscList(this, body) }
	async customerdiscOpen(body) { return await customer_customerdiscOpen(this, body) }
	async customerdiscUpdate(body) { return await customer_customerdiscUpdate(this, body)}
	async customerdiscCreate(body) { return await customer_customerdiscCreate(this, body) }
	async customerdiscDelete(body) { return await customer_customerdiscDelete(this, body) }
	async customerdiscDeleteRows(body) { return await customer_customerdiscDeleteRows(this, body) }
			
}	

// init module
async function customer_init(self, body) {
	const req = self.req

	// set sid untuk session ini, diperlukan ini agar session aktif
	req.session.sid = req.sessionID

	try {
		// ambil data app dari database
		const sql = 'select apps_id, apps_url from core."apps"'
		const result = await db.any(sql)

		const appsUrls = {}
		for (let row of result) {
			appsUrls[row.apps_id] = {
				url: row.apps_url
			}
		}

		const initialData = {
			userId: req.session.user.userId,
			userName: req.session.user.userName,
			userFullname: req.session.userFullname,
			sid: req.session.sid ,
			notifierId: Api.generateNotifierId(moduleName, req.sessionID),
			notifierSocket: req.app.locals.appConfig.notifierSocket,
			appName: req.app.locals.appConfig.appName,
			appsUrls: appsUrls,
			setting: {}
		}
		
		if (typeof Extender.customer_init === 'function') {
			// export async function customer_init(self, initialData) {}
			await Extender.customer_init(self, initialData)
		}

		return initialData
		
	} catch (err) {
		throw err
	}
}


// execute extender function
async function customer_execute(self, body) {
	const { fnName } = body

	if (fnName==null || fnName=='') {
		throw new Error('fnName belum didefinisikan di api call') 
	}

	if (typeof Extender[fnName] === 'function') {
		// export async function [fnName](self, db, body, customer_log) {}
		return await Extender[fnName](self, db, body, customer_log)
	} else {
		// api function extender tidak ditemukan
		throw new Error(`${fnName} tidak ditmukan di extender`)
	}
}


// data logging
async function customer_log(self, body, startTime, tablename, id, action, data={}, remark='') {
	const { source } = body
	const req = self.req
	const user_id = req.session.user.userId
	const user_name = req.session.user.userFullname
	const ipaddress = req.ip
	const metadata = JSON.stringify({...{source:source}, ...data})
	const endTime = process.hrtime.bigint();
	const executionTimeMs = Number((endTime - startTime) / 1_000_000n); // hasil dalam ms tanpa desimal
	
	const logdata = {id, user_id, user_name, moduleName, action, tablename, executionTimeMs, remark, metadata, ipaddress}
	const ret = await logger.log(logdata)
	return ret
}





async function customer_headerList(self, body) {
	const tablename = headerTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		searchtext: `customer_id=try_cast_bigint(\${searchtext}, 0) OR customer_name ILIKE '%' || \${searchtext} || '%'`,
	};

	try {
	
		// jika tidak ada default searchtext
		if (searchMap.searchtext===undefined) {
			throw new Error(`'searchtext' belum didefinisikan di searchMap`)	
		}
		

		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.headerListCriteria === 'function') {
			// export async function headerListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.headerListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort,
			limit:max_rows+1, 
			offset, 
			queryParams
		})

		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: customertype_name dari field customertype_name pada table public.customertype dimana (public.customertype.customertype_id = public.customer.customertype_id)
			{
				const { customertype_name } = await sqlUtil.lookupdb(db, 'public.customertype', 'customertype_id', row.customertype_id)
				row.customertype_name = customertype_name
			}
			// lookup: gender_name dari field gender_name pada table public.gender dimana (public.gender.gender_id = public.customer.gender_id)
			{
				const { gender_name } = await sqlUtil.lookupdb(db, 'public.gender', 'gender_id', row.gender_id)
				row.gender_name = gender_name
			}
			
			// pasang extender di sini
			if (typeof Extender.headerListRow === 'function') {
				// export async function headerListRow(self, row, args) {}
				await Extender.headerListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}

		return {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

	} catch (err) {
		throw err
	}
}

async function customer_headerOpen(self, body) {
	const tablename = headerTableName

	try {
		const { id } = body 
		const criteria = { customer_id: id }
		const searchMap = { customer_id: `customer_id = \${customer_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	

		// lookup: customertype_name dari field customertype_name pada table public.customertype dimana (public.customertype.customertype_id = public.customer.customertype_id)
		{
			const { customertype_name } = await sqlUtil.lookupdb(db, 'public.customertype', 'customertype_id', data.customertype_id)
			data.customertype_name = customertype_name
		}
		// lookup: gender_name dari field gender_name pada table public.gender dimana (public.gender.gender_id = public.customer.gender_id)
		{
			const { gender_name } = await sqlUtil.lookupdb(db, 'public.gender', 'gender_id', data.gender_id)
			data.gender_name = gender_name
		}
		

		// lookup data createby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}
		
		// pasang extender untuk olah data
		// export async function headerOpen(self, db, data) {}
		if (typeof Extender.headerOpen === 'function') {
			// export async function headerOpen(self, db, data) {}
			await Extender.headerOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}


async function customer_headerCreate(self, body) {
	const { source='customer', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._createby = user_id
		data._createdate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { section: 'header', doc_id:'' }

				
			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerCreating === 'function') {
				// export async function headerCreating(self, tx, data, seqdata, args) {}
				await Extender.headerCreating(self, tx, data, null, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerCreated === 'function') {
				// export async function headerCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.headerCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			customer_log(self, body, startTime, tablename, ret.customer_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function customer_headerUpdate(self, body) {
	const { source='customer', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._modifyby = user_id
		data._modifydate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerUpdating === 'function') {
				// export async function headerUpdating(self, tx, data) {}
				await Extender.headerUpdating(self, tx, data)
			}

			// eksekusi update
			const cmd = sqlUtil.createUpdateCommand(tablename, data, ['customer_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerUpdated === 'function') {
				// export async function headerUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.headerUpdated(self, tx, ret, data, logMetadata)
			}			

			// record log
			customer_log(self, body, startTime, tablename, data.customer_id, 'UPDATE')

			return ret
		})
		

		return result
	} catch (err) {
		throw err
	}
}


async function customer_headerDelete(self, body) {
	const { source, id } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {customer_id: id}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender headerDeleting
			if (typeof Extender.headerDeleting === 'function') {
				// export async function headerDeleting(self, tx, dataToRemove) {}
				await Extender.headerDeleting(self, tx, dataToRemove)
			}

			
			// hapus data customerdisc
			{
				const sql = `select * from ${customerdiscTableName} where customer_id=\${customer_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowcustomerdisc of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.customerdiscDeleting === 'function') {
						// export async function customerdiscDeleting(self, tx, rowcustomerdisc, logMetadata) {}
						await Extender.customerdiscDeleting(self, tx, rowcustomerdisc, logMetadata)
					}

					const param = {customerdisc_id: rowcustomerdisc.customerdisc_id}
					const cmd = sqlUtil.createDeleteCommand(customerdiscTableName, ['customerdisc_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.customerdiscDeleted === 'function') {
						// export async function customerdiscDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.customerdiscDeleted(self, tx, deletedRow, logMetadata)
					}					

					customer_log(self, body, startTime, customerdiscTableName, rowcustomerdisc.customerdisc_id, 'DELETE', {rowdata: deletedRow})
					customer_log(self, body, startTime, headerTableName, rowcustomerdisc.customer_id, 'DELETE ROW CUSTOMERDISC', {customerdisc_id: rowcustomerdisc.customerdisc_id, tablename: customerdiscTableName}, `removed: ${rowcustomerdisc.customerdisc_id}`)


				}	
			}

			
			

			// hapus data header
			const cmd = sqlUtil.createDeleteCommand(tablename, ['customer_id'])
			const deletedRow = await cmd.execute(dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender headerDeleted
			if (typeof Extender.headerDeleted === 'function') {
				// export async function headerDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.headerDeleted(self, tx, deletedRow, logMetadata)
			}

			// record log
			customer_log(self, body, startTime, tablename, id, 'DELETE', logMetadata)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}



// customerdisc	

async function customer_customerdiscList(self, body) {
	const tablename = customerdiscTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		customer_id: `customer_id=try_cast_bigint(\${customer_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.customerdisc_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.customerdiscListCriteria === 'function') {
			// export async function customerdiscListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.customerdiscListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			

			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function customer_customerdiscOpen(self, body) {
	const tablename = customerdiscTableName

	try {
		const { id } = body 
		const criteria = { customerdisc_id: id }
		const searchMap = { customerdisc_id: `customerdisc_id = \${customerdisc_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		

		// lookup data createby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function customerdiscOpen(self, db, data) {}
		if (typeof Extender.customerdiscOpen === 'function') {
			// export async function customerdiscOpen(self, db, data) {}
			await Extender.customerdiscOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function customer_customerdiscCreate(self, body) {
	const { source='customer', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = customerdiscTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._createby = user_id
		data._createdate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'customerdisc', 
				prefix: ''	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.prefix)
			data.customerdisc_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.customerdiscCreating === 'function') {
				// export async function customerdiscCreating(self, tx, data, seqdata, args) {}
				await Extender.customerdiscCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.customerdiscCreated === 'function') {
				// export async function customerdiscCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.customerdiscCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			customer_log(self, body, startTime, tablename, ret.customerdisc_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function customer_customerdiscUpdate(self, body) {
	const { source='customer', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = customerdiscTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._modifyby = user_id
		data._modifydate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.customerdiscUpdating === 'function') {
				// export async function customerdiscUpdating(self, tx, data) {}
				await Extender.customerdiscUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['customerdisc_id'])
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.customerdiscUpdated === 'function') {
				// export async function customerdiscUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.customerdiscUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			customer_log(self, body, startTime, tablename, data.customerdisc_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function customer_customerdiscDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = customerdiscTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {customerdisc_id: id}
			const sql = `select * from ${customerdiscTableName} where customerdisc_id=\${customerdisc_id}`
			const rowcustomerdisc = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.customerdiscDeleting === 'function') {
				// export async function customerdiscDeleting(self, tx, rowcustomerdisc, logMetadata) {}
				await Extender.customerdiscDeleting(self, tx, rowcustomerdisc, logMetadata)
			}

			const param = {customerdisc_id: rowcustomerdisc.customerdisc_id}
			const cmd = sqlUtil.createDeleteCommand(customerdiscTableName, ['customerdisc_id'])
			const deletedRow = await cmd.execute(param)

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.customerdiscDeleted === 'function') {
				// export async function customerdiscDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.customerdiscDeleted(self, tx, deletedRow, logMetadata)
			}					

			customer_log(self, body, startTime, customerdiscTableName, rowcustomerdisc.customerdisc_id, 'DELETE', {rowdata: deletedRow})
			customer_log(self, body, startTime, headerTableName, rowcustomerdisc.customer_id, 'DELETE ROW CUSTOMERDISC', {customerdisc_id: rowcustomerdisc.customerdisc_id, tablename: customerdiscTableName}, `removed: ${rowcustomerdisc.customerdisc_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function customer_customerdiscDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = customerdiscTableName


	try {

		let customer_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {customerdisc_id: id}
				const sql = `select * from ${customerdiscTableName} where customerdisc_id=\${customerdisc_id}`
				const rowcustomerdisc = await tx.oneOrNone(sql, dataToRemove)
				customer_id = rowcustomerdisc.customer_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.customerdiscDeleting === 'function') {
					// async function customerdiscDeleting(self, tx, rowcustomerdisc, logMetadata) {}
					await Extender.customerdiscDeleting(self, tx, rowcustomerdisc, logMetadata)
				}

				const param = {customerdisc_id: rowcustomerdisc.customerdisc_id}
				const cmd = sqlUtil.createDeleteCommand(customerdiscTableName, ['customerdisc_id'])
				const deletedRow = await cmd.execute(param)

				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.customerdiscDeleted === 'function') {
					// export async function customerdiscDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.customerdiscDeleted(self, tx, deletedRow, logMetadata)
				}					

				customer_log(self, body, startTime, customerdiscTableName, rowcustomerdisc.customerdisc_id, 'DELETE', {rowdata: deletedRow})
				customer_log(self, body, startTime, headerTableName, rowcustomerdisc.customer_id, 'DELETE ROW CUSTOMERDISC', {customerdisc_id: rowcustomerdisc.customerdisc_id, tablename: customerdiscTableName}, `removed: ${rowcustomerdisc.customerdisc_id}`)
			}
		})
		

		const res = {
			deleted: true,
			customer_id: customer_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'customerdiscRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function customerdiscRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}

	