/***************************************************************** 
 * this script is generated by fgta5 generator version 1.2
 * DO NOT modify this script! All modification will lost on regeneration
 **************************************************************** */

import pgp from 'pg-promise';

import db from '@agung_dhewe/webapps/src/db.js'
import Api from '@agung_dhewe/webapps/src/api.js'
import sqlUtil from '@agung_dhewe/pgsqlc'
import context from '@agung_dhewe/webapps/src/context.js'  
import logger from '@agung_dhewe/webapps/src/logger.js'
import { createSequencerLine } from '@agung_dhewe/webapps/src/sequencerline.js' 

import * as Extender from './extenders/role.apiext.js'

const moduleName = 'role'
const headerSectionName = 'header'
const headerTableName = 'core.role' 
const permissionTableName = 'core.rolepermission'  	

// api: account
export default class extends Api {
	constructor(req, res, next) {
		super(req, res, next);
		Api.cekLogin(req)
	}


	// dipanggil dengan model snake syntax
	// contoh: header-list
	//         header-open-data
	async init(body) { return await role_init(this, body) }

	// extender call
	async execute(body) { return await role_execute(this, body) }

	// header
	async headerList(body) { return await role_headerList(this, body) }
	async headerOpen(body) { return await role_headerOpen(this, body) }
	async headerUpdate(body) { return await role_headerUpdate(this, body)}
	async headerCreate(body) { return await role_headerCreate(this, body)}
	async headerDelete(body) { return await role_headerDelete(this, body) }

	
	// permission	
	async permissionList(body) { return await role_permissionList(this, body) }
	async permissionOpen(body) { return await role_permissionOpen(this, body) }
	async permissionUpdate(body) { return await role_permissionUpdate(this, body)}
	async permissionCreate(body) { return await role_permissionCreate(this, body) }
	async permissionDelete(body) { return await role_permissionDelete(this, body) }
	async permissionDeleteRows(body) { return await role_permissionDeleteRows(this, body) }
			
}	

// init module
async function role_init(self, body) {
	const req = self.req

	// set sid untuk session ini, diperlukan ini agar session aktif
	req.session.sid = req.sessionID

	try {
		// ambil data app dari database
		const sql = 'select apps_id, apps_url from core."apps"'
		const result = await db.any(sql)

		const appsUrls = {}
		for (let row of result) {
			appsUrls[row.apps_id] = {
				url: row.apps_url
			}
		}

		const initialData = {
			userId: req.session.user.userId,
			userName: req.session.user.userName,
			userFullname: req.session.userFullname,
			sid: req.session.sid ,
			notifierId: Api.generateNotifierId(moduleName, req.sessionID),
			notifierSocket: req.app.locals.appConfig.notifierSocket,
			appName: req.app.locals.appConfig.appName,
			appsUrls: appsUrls,
			setting: {}
		}
		
		if (typeof Extender.role_init === 'function') {
			// export async function role_init(self, initialData) {}
			await Extender.role_init(self, initialData)
		}

		return initialData
		
	} catch (err) {
		throw err
	}
}


// execute extender function
async function role_execute(self, body) {
	const { fnName } = body

	if (fnName==null || fnName=='') {
		throw new Error('fnName belum didefinisikan di api call') 
	}

	if (typeof Extender[fnName] === 'function') {
		// export async function [fnName](self, db, body, role_log) {}
		return await Extender[fnName](self, db, body, role_log)
	} else {
		// api function extender tidak ditemukan
		throw new Error(`${fnName} tidak ditmukan di extender`)
	}
}


// data logging
async function role_log(self, body, startTime, tablename, id, action, data={}, remark='') {
	const { source } = body
	const req = self.req
	const user_id = req.session.user.userId
	const user_name = req.session.user.userFullname
	const ipaddress = req.ip
	const metadata = JSON.stringify({...{source:source}, ...data})
	const endTime = process.hrtime.bigint();
	const executionTimeMs = Number((endTime - startTime) / 1_000_000n); // hasil dalam ms tanpa desimal
	
	const logdata = {id, user_id, user_name, moduleName, action, tablename, executionTimeMs, remark, metadata, ipaddress}
	const ret = await logger.log(logdata)
	return ret
}





async function role_headerList(self, body) {
	const tablename = headerTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		searchtext: `role_name ILIKE '%' || \${searchtext} || '%' OR role_descr ILIKE '%' || \${searchtext} || '%'`,
	};

	try {
	
		// jika tidak ada default searchtext
		if (searchMap.searchtext===undefined) {
			throw new Error(`'searchtext' belum didefinisikan di searchMap`)	
		}
		

		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.headerListCriteria === 'function') {
			// export async function headerListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.headerListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort,
			limit:max_rows+1, 
			offset, 
			queryParams
		})

		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			
			// pasang extender di sini
			if (typeof Extender.headerListRow === 'function') {
				// export async function headerListRow(self, row, args) {}
				await Extender.headerListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}

		return {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

	} catch (err) {
		throw err
	}
}

async function role_headerOpen(self, body) {
	const tablename = headerTableName

	try {
		const { id } = body 
		const criteria = { role_id: id }
		const searchMap = { role_id: `role_id = \${role_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	

		

		// lookup data createby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}
		
		// pasang extender untuk olah data
		// export async function headerOpen(self, db, data) {}
		if (typeof Extender.headerOpen === 'function') {
			// export async function headerOpen(self, db, data) {}
			await Extender.headerOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}


async function role_headerCreate(self, body) {
	const { source='role', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._createby = user_id
		data._createdate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { section: 'header', doc_id:'' }

				
			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerCreating === 'function') {
				// export async function headerCreating(self, tx, data, seqdata, args) {}
				await Extender.headerCreating(self, tx, data, null, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data, ['role_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerCreated === 'function') {
				// export async function headerCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.headerCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			role_log(self, body, startTime, tablename, ret.role_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function role_headerUpdate(self, body) {
	const { source='role', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._modifyby = user_id
		data._modifydate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerUpdating === 'function') {
				// export async function headerUpdating(self, tx, data) {}
				await Extender.headerUpdating(self, tx, data)
			}

			// eksekusi update
			const cmd = sqlUtil.createUpdateCommand(tablename, data, ['role_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerUpdated === 'function') {
				// export async function headerUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.headerUpdated(self, tx, ret, data, logMetadata)
			}			

			// record log
			role_log(self, body, startTime, tablename, data.role_id, 'UPDATE')

			return ret
		})
		

		return result
	} catch (err) {
		throw err
	}
}


async function role_headerDelete(self, body) {
	const { source, id } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {role_id: id}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender headerDeleting
			if (typeof Extender.headerDeleting === 'function') {
				// export async function headerDeleting(self, tx, dataToRemove) {}
				await Extender.headerDeleting(self, tx, dataToRemove)
			}

			
			// hapus data permission
			{
				const sql = `select * from ${permissionTableName} where role_id=\${role_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowpermission of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.permissionDeleting === 'function') {
						// export async function permissionDeleting(self, tx, rowpermission, logMetadata) {}
						await Extender.permissionDeleting(self, tx, rowpermission, logMetadata)
					}

					const param = {rolepermission_id: rowpermission.rolepermission_id}
					const cmd = sqlUtil.createDeleteCommand(permissionTableName, ['rolepermission_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.permissionDeleted === 'function') {
						// export async function permissionDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.permissionDeleted(self, tx, deletedRow, logMetadata)
					}					

					role_log(self, body, startTime, permissionTableName, rowpermission.rolepermission_id, 'DELETE', {rowdata: deletedRow})
					role_log(self, body, startTime, headerTableName, rowpermission.role_id, 'DELETE ROW PERMISSION', {rolepermission_id: rowpermission.rolepermission_id, tablename: permissionTableName}, `removed: ${rowpermission.rolepermission_id}`)


				}	
			}

			
			

			// hapus data header
			const cmd = sqlUtil.createDeleteCommand(tablename, ['role_id'])
			const deletedRow = await cmd.execute(dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender headerDeleted
			if (typeof Extender.headerDeleted === 'function') {
				// export async function headerDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.headerDeleted(self, tx, deletedRow, logMetadata)
			}

			// record log
			role_log(self, body, startTime, tablename, id, 'DELETE', logMetadata)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}



// permission	

async function role_permissionList(self, body) {
	const tablename = permissionTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		role_id: `role_id=try_cast_bigint(\${role_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.rolepermission_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.permissionListCriteria === 'function') {
			// export async function permissionListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.permissionListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: permission_name dari field permission_name pada table core.permission dimana (core.permission.permission_id = core.role.permission_id)
			{
				const { permission_name } = await sqlUtil.lookupdb(db, 'core.permission', 'permission_id', row.permission_id)
				row.permission_name = permission_name
			}
			

			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function role_permissionOpen(self, body) {
	const tablename = permissionTableName

	try {
		const { id } = body 
		const criteria = { rolepermission_id: id }
		const searchMap = { rolepermission_id: `rolepermission_id = \${rolepermission_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		// lookup: permission_name dari field permission_name pada table core.permission dimana (core.permission.permission_id = core.role.permission_id)
		{
			const { permission_name } = await sqlUtil.lookupdb(db, 'core.permission', 'permission_id', data.permission_id)
			data.permission_name = permission_name
		}
		

		// lookup data createby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function permissionOpen(self, db, data) {}
		if (typeof Extender.permissionOpen === 'function') {
			// export async function permissionOpen(self, db, data) {}
			await Extender.permissionOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function role_permissionCreate(self, body) {
	const { source='role', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = permissionTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._createby = user_id
		data._createdate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'permission', 
				prefix: ''	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.prefix)
			data.rolepermission_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.permissionCreating === 'function') {
				// export async function permissionCreating(self, tx, data, seqdata, args) {}
				await Extender.permissionCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.permissionCreated === 'function') {
				// export async function permissionCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.permissionCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			role_log(self, body, startTime, tablename, ret.rolepermission_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function role_permissionUpdate(self, body) {
	const { source='role', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = permissionTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._modifyby = user_id
		data._modifydate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.permissionUpdating === 'function') {
				// export async function permissionUpdating(self, tx, data) {}
				await Extender.permissionUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['rolepermission_id'])
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.permissionUpdated === 'function') {
				// export async function permissionUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.permissionUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			role_log(self, body, startTime, tablename, data.rolepermission_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function role_permissionDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = permissionTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {rolepermission_id: id}
			const sql = `select * from ${permissionTableName} where rolepermission_id=\${rolepermission_id}`
			const rowpermission = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.permissionDeleting === 'function') {
				// export async function permissionDeleting(self, tx, rowpermission, logMetadata) {}
				await Extender.permissionDeleting(self, tx, rowpermission, logMetadata)
			}

			const param = {rolepermission_id: rowpermission.rolepermission_id}
			const cmd = sqlUtil.createDeleteCommand(permissionTableName, ['rolepermission_id'])
			const deletedRow = await cmd.execute(param)

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.permissionDeleted === 'function') {
				// export async function permissionDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.permissionDeleted(self, tx, deletedRow, logMetadata)
			}					

			role_log(self, body, startTime, permissionTableName, rowpermission.rolepermission_id, 'DELETE', {rowdata: deletedRow})
			role_log(self, body, startTime, headerTableName, rowpermission.role_id, 'DELETE ROW PERMISSION', {rolepermission_id: rowpermission.rolepermission_id, tablename: permissionTableName}, `removed: ${rowpermission.rolepermission_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function role_permissionDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = permissionTableName


	try {

		let role_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {rolepermission_id: id}
				const sql = `select * from ${permissionTableName} where rolepermission_id=\${rolepermission_id}`
				const rowpermission = await tx.oneOrNone(sql, dataToRemove)
				role_id = rowpermission.role_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.permissionDeleting === 'function') {
					// async function permissionDeleting(self, tx, rowpermission, logMetadata) {}
					await Extender.permissionDeleting(self, tx, rowpermission, logMetadata)
				}

				const param = {rolepermission_id: rowpermission.rolepermission_id}
				const cmd = sqlUtil.createDeleteCommand(permissionTableName, ['rolepermission_id'])
				const deletedRow = await cmd.execute(param)

				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.permissionDeleted === 'function') {
					// export async function permissionDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.permissionDeleted(self, tx, deletedRow, logMetadata)
				}					

				role_log(self, body, startTime, permissionTableName, rowpermission.rolepermission_id, 'DELETE', {rowdata: deletedRow})
				role_log(self, body, startTime, headerTableName, rowpermission.role_id, 'DELETE ROW PERMISSION', {rolepermission_id: rowpermission.rolepermission_id, tablename: permissionTableName}, `removed: ${rowpermission.rolepermission_id}`)
			}
		})
		

		const res = {
			deleted: true,
			role_id: role_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'permissionRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function permissionRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}

	