/***************************************************************** 
 * this script is generated by fgta5 generator version 1.2
 * DO NOT modify this script! All modification will lost on regeneration
 **************************************************************** */

import pgp from 'pg-promise';

import db from '@agung_dhewe/webapps/src/db.js'
import Api from '@agung_dhewe/webapps/src/api.js'
import sqlUtil from '@agung_dhewe/pgsqlc'
import context from '@agung_dhewe/webapps/src/context.js'  
import logger from '@agung_dhewe/webapps/src/logger.js'
import { createSequencerLine } from '@agung_dhewe/webapps/src/sequencerline.js' 

import * as Extender from './extenders/site.apiext.js'

const moduleName = 'site'
const headerSectionName = 'header'
const headerTableName = 'public.site' 
const sitebrandTableName = 'public.sitebrand'  	

// api: account
export default class extends Api {
	constructor(req, res, next) {
		super(req, res, next);
		Api.cekLogin(req)
	}


	// dipanggil dengan model snake syntax
	// contoh: header-list
	//         header-open-data
	async init(body) { return await site_init(this, body) }

	// extender call
	async execute(body) { return await site_execute(this, body) }

	// header
	async headerList(body) { return await site_headerList(this, body) }
	async headerOpen(body) { return await site_headerOpen(this, body) }
	async headerUpdate(body) { return await site_headerUpdate(this, body)}
	async headerCreate(body) { return await site_headerCreate(this, body)}
	async headerDelete(body) { return await site_headerDelete(this, body) }

	
	// sitebrand	
	async sitebrandList(body) { return await site_sitebrandList(this, body) }
	async sitebrandOpen(body) { return await site_sitebrandOpen(this, body) }
	async sitebrandUpdate(body) { return await site_sitebrandUpdate(this, body)}
	async sitebrandCreate(body) { return await site_sitebrandCreate(this, body) }
	async sitebrandDelete(body) { return await site_sitebrandDelete(this, body) }
	async sitebrandDeleteRows(body) { return await site_sitebrandDeleteRows(this, body) }
			
}	

// init module
async function site_init(self, body) {
	const req = self.req

	// set sid untuk session ini, diperlukan ini agar session aktif
	req.session.sid = req.sessionID

	try {
		// ambil data app dari database
		const sql = 'select apps_id, apps_url from core."apps"'
		const result = await db.any(sql)

		const appsUrls = {}
		for (let row of result) {
			appsUrls[row.apps_id] = {
				url: row.apps_url
			}
		}

		const initialData = {
			userId: req.session.user.userId,
			userName: req.session.user.userName,
			userFullname: req.session.userFullname,
			sid: req.session.sid ,
			notifierId: Api.generateNotifierId(moduleName, req.sessionID),
			notifierSocket: req.app.locals.appConfig.notifierSocket,
			appName: req.app.locals.appConfig.appName,
			appsUrls: appsUrls,
			setting: {}
		}
		
		if (typeof Extender.site_init === 'function') {
			// export async function site_init(self, initialData) {}
			await Extender.site_init(self, initialData)
		}

		return initialData
		
	} catch (err) {
		throw err
	}
}


// execute extender function
async function site_execute(self, body) {
	const { fnName } = body

	if (fnName==null || fnName=='') {
		throw new Error('fnName belum didefinisikan di api call') 
	}

	if (typeof Extender[fnName] === 'function') {
		// export async function [fnName](self, db, body, site_log) {}
		return await Extender[fnName](self, db, body, site_log)
	} else {
		// api function extender tidak ditemukan
		throw new Error(`${fnName} tidak ditmukan di extender`)
	}
}


// data logging
async function site_log(self, body, startTime, tablename, id, action, data={}, remark='') {
	const { source } = body
	const req = self.req
	const user_id = req.session.user.userId
	const user_name = req.session.user.userFullname
	const ipaddress = req.ip
	const metadata = JSON.stringify({...{source:source}, ...data})
	const endTime = process.hrtime.bigint();
	const executionTimeMs = Number((endTime - startTime) / 1_000_000n); // hasil dalam ms tanpa desimal
	
	const logdata = {id, user_id, user_name, moduleName, action, tablename, executionTimeMs, remark, metadata, ipaddress}
	const ret = await logger.log(logdata)
	return ret
}





async function site_headerList(self, body) {
	const tablename = headerTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		searchtext: `site_name ILIKE '%' || \${searchtext} || '%' OR site_namereport ILIKE '%' || \${searchtext} || '%'`,
	};

	try {
	
		// jika tidak ada default searchtext
		if (searchMap.searchtext===undefined) {
			throw new Error(`'searchtext' belum didefinisikan di searchMap`)	
		}
		

		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.headerListCriteria === 'function') {
			// export async function headerListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.headerListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort,
			limit:max_rows+1, 
			offset, 
			queryParams
		})

		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			
			// pasang extender di sini
			if (typeof Extender.headerListRow === 'function') {
				// export async function headerListRow(self, row, args) {}
				await Extender.headerListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}

		return {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

	} catch (err) {
		throw err
	}
}

async function site_headerOpen(self, body) {
	const tablename = headerTableName

	try {
		const { id } = body 
		const criteria = { site_id: id }
		const searchMap = { site_id: `site_id = \${site_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	

		

		// lookup data createby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}
		
		// pasang extender untuk olah data
		// export async function headerOpen(self, db, data) {}
		if (typeof Extender.headerOpen === 'function') {
			// export async function headerOpen(self, db, data) {}
			await Extender.headerOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}


async function site_headerCreate(self, body) {
	const { source='site', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._createby = user_id
		data._createdate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { section: 'header', doc_id:'SITE' }

				
			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerCreating === 'function') {
				// export async function headerCreating(self, tx, data, seqdata, args) {}
				await Extender.headerCreating(self, tx, data, null, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerCreated === 'function') {
				// export async function headerCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.headerCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			site_log(self, body, startTime, tablename, ret.site_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function site_headerUpdate(self, body) {
	const { source='site', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._modifyby = user_id
		data._modifydate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengelohan data sebelum disimpan, lakukan di extender headerCreating
			if (typeof Extender.headerUpdating === 'function') {
				// export async function headerUpdating(self, tx, data) {}
				await Extender.headerUpdating(self, tx, data)
			}

			// eksekusi update
			const cmd = sqlUtil.createUpdateCommand(tablename, data, ['site_id'])
			const ret = await cmd.execute(data)

			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.headerUpdated === 'function') {
				// export async function headerUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.headerUpdated(self, tx, ret, data, logMetadata)
			}			

			// record log
			site_log(self, body, startTime, tablename, data.site_id, 'UPDATE')

			return ret
		})
		

		return result
	} catch (err) {
		throw err
	}
}


async function site_headerDelete(self, body) {
	const { source, id } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = headerTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {site_id: id}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender headerDeleting
			if (typeof Extender.headerDeleting === 'function') {
				// export async function headerDeleting(self, tx, dataToRemove) {}
				await Extender.headerDeleting(self, tx, dataToRemove)
			}

			
			// hapus data sitebrand
			{
				const sql = `select * from ${sitebrandTableName} where site_id=\${site_id}`
				const rows = await tx.any(sql, dataToRemove)
				for (let rowsitebrand of rows) {
					
					const logMetadata = {}
					
					// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
					if (typeof Extender.sitebrandDeleting === 'function') {
						// export async function sitebrandDeleting(self, tx, rowsitebrand, logMetadata) {}
						await Extender.sitebrandDeleting(self, tx, rowsitebrand, logMetadata)
					}

					const param = {sitebrand_id: rowsitebrand.sitebrand_id}
					const cmd = sqlUtil.createDeleteCommand(sitebrandTableName, ['sitebrand_id'])
					const deletedRow = await cmd.execute(param)

					// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
					if (typeof Extender.sitebrandDeleted === 'function') {
						// export async function sitebrandDeleted(self, tx, deletedRow, logMetadata) {}
						await Extender.sitebrandDeleted(self, tx, deletedRow, logMetadata)
					}					

					site_log(self, body, startTime, sitebrandTableName, rowsitebrand.sitebrand_id, 'DELETE', {rowdata: deletedRow})
					site_log(self, body, startTime, headerTableName, rowsitebrand.site_id, 'DELETE ROW SITEBRAND', {sitebrand_id: rowsitebrand.sitebrand_id, tablename: sitebrandTableName}, `removed: ${rowsitebrand.sitebrand_id}`)


				}	
			}

			
			

			// hapus data header
			const cmd = sqlUtil.createDeleteCommand(tablename, ['site_id'])
			const deletedRow = await cmd.execute(dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender headerDeleted
			if (typeof Extender.headerDeleted === 'function') {
				// export async function headerDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.headerDeleted(self, tx, deletedRow, logMetadata)
			}

			// record log
			site_log(self, body, startTime, tablename, id, 'DELETE', logMetadata)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}



// sitebrand	

async function site_sitebrandList(self, body) {
	const tablename = sitebrandTableName
	const { criteria={}, limit=0, offset=0, columns=[], sort={} } = body
	const searchMap = {
		site_id: `site_id=try_cast_bigint(\${site_id}, 0)`,
	};


	if (Object.keys(sort).length === 0) {
		sort.sitebrand_id = 'asc'
	}


	try {
	
		// hilangkan criteria '' atau null
		for (var cname in criteria) {
			if (criteria[cname]==='' || criteria[cname]===null) {
				delete criteria[cname]
			}
		}

		const args = { db, criteria, tablename }

		// apabila ada keperluan untuk recompose criteria
		if (typeof Extender.sitebrandListCriteria === 'function') {
			// export async function sitebrandListCriteria(self, db, searchMap, criteria, sort, columns, args) {}
			await Extender.sitebrandListCriteria(self, db, searchMap, criteria, sort, columns, args)
		}

		var max_rows = limit==0 ? 10 : limit
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename: args.tablename, 
			columns, 
			whereClause, 
			sort: args.sqlSort ?? sort, 
			limit:max_rows+1, 
			offset, 
			queryParams
		})
		const rows = await db.any(sql, queryParams);

		
		var i = 0
		const data = []
		for (var row of rows) {
			i++
			if (i>max_rows) { break }

			// lookup: brand_name dari field brand_name pada table public.brand dimana (public.brand.brand_id = public.site.brand_id)
			{
				const { brand_name } = await sqlUtil.lookupdb(db, 'public.brand', 'brand_id', row.brand_id)
				row.brand_name = brand_name
			}
			

			// pasang extender di sini
			if (typeof Extender.detilListRow === 'function') {
				// export async function detilListRow(self, row, args) {}
				await Extender.detilListRow(self, row, args)
			}

			data.push(row)
		}

		var nextoffset = null
		if (rows.length>max_rows) {
			nextoffset = offset+max_rows
		}


		const listData = {
			criteria: criteria,
			limit:  max_rows,
			nextoffset: nextoffset,
			data: data
		}

		if (typeof Extender.detilList === 'function') {
			// export async function detilList(self, listData, args) {}
			await Extender.detilList(self, listData, args)
		}

		return listData
	} catch (err) {
		throw err
	}
}

async function site_sitebrandOpen(self, body) {
	const tablename = sitebrandTableName

	try {
		const { id } = body 
		const criteria = { sitebrand_id: id }
		const searchMap = { sitebrand_id: `sitebrand_id = \${sitebrand_id}`}
		const {whereClause, queryParams} = sqlUtil.createWhereClause(criteria, searchMap) 
		const sql = sqlUtil.createSqlSelect({
			tablename, 
			columns:[], 
			whereClause, 
			sort:{}, 
			limit:0, 
			offset:0, 
			queryParams
		})
		const data = await db.one(sql, queryParams);
		if (data==null) { 
			throw new Error(`[${tablename}] data dengan id '${id}' tidak ditemukan`) 
		}	


		// lookup: brand_name dari field brand_name pada table public.brand dimana (public.brand.brand_id = public.site.brand_id)
		{
			const { brand_name } = await sqlUtil.lookupdb(db, 'public.brand', 'brand_id', data.brand_id)
			data.brand_name = brand_name
		}
		

		// lookup data createby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._createby)
			data._createby = user_fullname ?? ''
		}

		// lookup data modifyby
		{
			const { user_fullname } = await sqlUtil.lookupdb(db, 'core.user', 'user_id', data._modifyby)
			data._modifyby = user_fullname ?? ''
		}	


		// pasang extender untuk olah data
		// export async function sitebrandOpen(self, db, data) {}
		if (typeof Extender.sitebrandOpen === 'function') {
			// export async function sitebrandOpen(self, db, data) {}
			await Extender.sitebrandOpen(self, db, data)
		}

		return data
	} catch (err) {
		throw err
	}
}

async function site_sitebrandCreate(self, body) {
	const { source='site', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = sitebrandTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._createby = user_id
		data._createdate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			const args = { 
				section: 'sitebrand', 
				prefix: 'SITE'	
			}

			const sequencer = createSequencerLine(tx, {})


			if (typeof Extender.sequencerSetup === 'function') {
				// jika ada keperluan menambahkan code block/cluster di sequencer
				// dapat diimplementasikan di exterder sequencerSetup 
				// export async function sequencerSetup(self, tx, sequencer, data, args) {}
				await Extender.sequencerSetup(self, tx, sequencer, data, args)
			}


			const seqdata = await sequencer.increment(args.prefix)
			data.sitebrand_id = seqdata.id

			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.sitebrandCreating === 'function') {
				// export async function sitebrandCreating(self, tx, data, seqdata, args) {}
				await Extender.sitebrandCreating(self, tx, data, seqdata, args)
			}

			const cmd = sqlUtil.createInsertCommand(tablename, data)
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.sitebrandCreated === 'function') {
				// export async function sitebrandCreated(self, tx, ret, data, logMetadata, args) {}
				await Extender.sitebrandCreated(self, tx, ret, data, logMetadata, args)
			}

			// record log
			site_log(self, body, startTime, tablename, ret.sitebrand_id, 'CREATE', logMetadata)

			return ret
		})

		return result
	} catch (err) {
		throw err
	}
}

async function site_sitebrandUpdate(self, body) {
	const { source='site', data={} } = body
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = sitebrandTableName

	try {

		// parse uploaded data
		const files = Api.parseUploadData(data, req.files)


		data._modifyby = user_id
		data._modifydate = (new Date()).toISOString()

		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)


			// apabila ada keperluan pengolahan data SEBELUM disimpan
			if (typeof Extender.sitebrandUpdating === 'function') {
				// export async function sitebrandUpdating(self, tx, data) {}
				await Extender.sitebrandUpdating(self, tx, data)
			}			
			
			const cmd =  sqlUtil.createUpdateCommand(tablename, data, ['sitebrand_id'])
			const ret = await cmd.execute(data)
			
			const logMetadata = {}

			// apabila ada keperluan pengelohan data setelah disimpan, lakukan di extender headerCreated
			if (typeof Extender.sitebrandUpdated === 'function') {
				// export async function sitebrandUpdated(self, tx, ret, data, logMetadata) {}
				await Extender.sitebrandUpdated(self, tx, ret, data, logMetadata)
			}

			// record log
			site_log(self, body, startTime, tablename, data.sitebrand_id, 'UPDATE', logMetadata)

			return ret
		})
	
		return result
	} catch (err) {
		throw err
	}
}

async function site_sitebrandDelete(self, body) {
	const { source, id } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint()
	const tablename = sitebrandTableName

	try {

		const deletedRow = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			const dataToRemove = {sitebrand_id: id}
			const sql = `select * from ${sitebrandTableName} where sitebrand_id=\${sitebrand_id}`
			const rowsitebrand = await tx.oneOrNone(sql, dataToRemove)

			const logMetadata = {}

			// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
			if (typeof Extender.sitebrandDeleting === 'function') {
				// export async function sitebrandDeleting(self, tx, rowsitebrand, logMetadata) {}
				await Extender.sitebrandDeleting(self, tx, rowsitebrand, logMetadata)
			}

			const param = {sitebrand_id: rowsitebrand.sitebrand_id}
			const cmd = sqlUtil.createDeleteCommand(sitebrandTableName, ['sitebrand_id'])
			const deletedRow = await cmd.execute(param)

			// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
			if (typeof Extender.sitebrandDeleted === 'function') {
				// export async function sitebrandDeleted(self, tx, deletedRow, logMetadata) {}
				await Extender.sitebrandDeleted(self, tx, deletedRow, logMetadata)
			}					

			site_log(self, body, startTime, sitebrandTableName, rowsitebrand.sitebrand_id, 'DELETE', {rowdata: deletedRow})
			site_log(self, body, startTime, headerTableName, rowsitebrand.site_id, 'DELETE ROW SITEBRAND', {sitebrand_id: rowsitebrand.sitebrand_id, tablename: sitebrandTableName}, `removed: ${rowsitebrand.sitebrand_id}`)

			return deletedRow
		})
	

		return deletedRow
	} catch (err) {
		throw err
	}
}

async function site_sitebrandDeleteRows(self, body) {
	const { data } = body 
	const req = self.req
	const user_id = req.session.user.userId
	const startTime = process.hrtime.bigint();
	const tablename = sitebrandTableName


	try {

		let site_id
		const result = await db.tx(async tx=>{
			sqlUtil.connect(tx)

			for (let id of data) {
				const dataToRemove = {sitebrand_id: id}
				const sql = `select * from ${sitebrandTableName} where sitebrand_id=\${sitebrand_id}`
				const rowsitebrand = await tx.oneOrNone(sql, dataToRemove)
				site_id = rowsitebrand.site_id

				const logMetadata = {}

				
				// apabila ada keperluan pengelohan data sebelum dihapus, lakukan di extender
				if (typeof Extender.sitebrandDeleting === 'function') {
					// async function sitebrandDeleting(self, tx, rowsitebrand, logMetadata) {}
					await Extender.sitebrandDeleting(self, tx, rowsitebrand, logMetadata)
				}

				const param = {sitebrand_id: rowsitebrand.sitebrand_id}
				const cmd = sqlUtil.createDeleteCommand(sitebrandTableName, ['sitebrand_id'])
				const deletedRow = await cmd.execute(param)

				// apabila ada keperluan pengelohan data setelah dihapus, lakukan di extender
				if (typeof Extender.sitebrandDeleted === 'function') {
					// export async function sitebrandDeleted(self, tx, deletedRow, logMetadata) {}
					await Extender.sitebrandDeleted(self, tx, deletedRow, logMetadata)
				}					

				site_log(self, body, startTime, sitebrandTableName, rowsitebrand.sitebrand_id, 'DELETE', {rowdata: deletedRow})
				site_log(self, body, startTime, headerTableName, rowsitebrand.site_id, 'DELETE ROW SITEBRAND', {sitebrand_id: rowsitebrand.sitebrand_id, tablename: sitebrandTableName}, `removed: ${rowsitebrand.sitebrand_id}`)
			}
		})
		

		const res = {
			deleted: true,
			site_id: site_id,
			message: ''
		}

		// apabila ada keperluan update info / pemrosesan data setelah hapus multirow, lakukan di extender
		const fn_name = 'sitebrandRowsDeleted'
		const fn = Extender[fn_name]
		if (typeof fn === 'function') {
			// export async function sitebrandRowsDeleted(self, db, res) {}
			await fn(self, db, res)
		}

		return res
	} catch (err) {
		throw err
	}	
}

	